import json

words = [
    ("one","wʌn","一","I have one apple."),
    ("two","tuː","二","I have two books."),
    ("three","θriː","三","There are three cats."),
    ("four","fɔː","四","Four plus two is six."),
    ("five","faɪv","五","I am five years old."),
    ("six","sɪks","六","Six friends played together."),
    ("seven","ˈsevən","七","She is seven years old."),
    ("eight","eɪt","八","Eight o'clock in the morning."),
    ("nine","naɪn","九","I have nine pencils."),
    ("ten","ten","十","Count from one to ten."),
    ("red","red","红色","The apple is red."),
    ("blue","bluː","蓝色","The sky is blue."),
    ("yellow","ˈjeloʊ","黄色","The banana is yellow."),
    ("green","griːn","绿色","The grass is green."),
    ("white","waɪt","白色","The snow is white."),
    ("black","blæk","黑色","The cat is black."),
    ("orange","ˈɔːrɪndʒ","橙色","The orange is sweet."),
    ("pink","pɪŋk","粉色","Her bag is pink."),
    ("purple","ˈpɜːrpəl","紫色","Grapes can be purple."),
    ("brown","braʊn","棕色","The bear is brown."),
    ("I","aɪ","我","I am a student."),
    ("you","juː","你","You are my friend."),
    ("he","hiː","他","He is my father."),
    ("she","ʃiː","她","She is my mother."),
    ("it","ɪt","它","It is a cat."),
    ("we","wiː","我们","We are in the same class."),
    ("they","ðeɪ","他们","They are playing games."),
    ("my","maɪ","我的","This is my book."),
    ("your","jɔːr","你的","Is this your bag?"),
    ("his","hɪz","他的","This is his desk."),
    ("her","hɜːr","她的","That is her name."),
    ("mother","ˈmʌðər","妈妈","My mother cooks dinner."),
    ("father","ˈfɑːðər","爸爸","My father drives a car."),
    ("brother","ˈbrʌðər","哥哥/弟弟","I have one brother."),
    ("sister","ˈsɪstər","姐姐/妹妹","My sister is tall."),
    ("grandma","ˈɡrænmɑː","奶奶/外婆","Grandma makes cookies."),
    ("grandpa","ˈɡrænpɑː","爷爷/外公","Grandpa reads newspapers."),
    ("friend","frend","朋友","She is my best friend."),
    ("family","ˈfæməli","家庭","I love my family."),
    ("boy","bɔɪ","男孩","The boy is playing football."),
    ("girl","ɡɜːrl","女孩","The girl is reading a book."),
    ("man","mæn","男人","The man is a teacher."),
    ("woman","ˈwʊmən","女人","The woman is a doctor."),
    ("child","tʃaɪld","孩子","The child is sleeping."),
    ("children","ˈtʃɪldrən","孩子们","The children are playing outside."),
    ("teacher","ˈtiːtʃər","老师","Our teacher is very kind."),
    ("doctor","ˈdɑːktər","医生","The doctor helps sick people."),
    ("nurse","nɜːrs","护士","The nurse is very caring."),
    ("policeman","pəˈliːsmən","警察","The policeman directs traffic."),
    ("driver","ˈdraɪvər","司机","The bus driver is careful."),
    ("farmer","ˈfɑːrmər","农民","The farmer grows vegetables."),
    ("student","ˈstuːdənt","学生","I am a student in Class One."),
    ("cat","kæt","猫","The cat likes fish."),
    ("dog","dɔːɡ","狗","The dog barks loudly."),
    ("bird","bɜːrd","鸟","The bird sings sweetly."),
    ("fish","fɪʃ","鱼","The fish swims in water."),
    ("rabbit","ˈræbɪt","兔子","The rabbit has long ears."),
    ("mouse","maʊs","老鼠","The mouse is very small."),
    ("elephant","ˈelɪfənt","大象","The elephant is very big."),
    ("monkey","ˈmʌŋki","猴子","The monkey swings on trees."),
    ("panda","ˈpændə","熊猫","Pandas only live in China."),
    ("tiger","ˈtaɪɡər","老虎","The tiger runs very fast."),
    ("lion","ˈlaɪən","狮子","The lion is called the king of animals."),
    ("zebra","ˈziːbrə","斑马","The zebra has black and white stripes."),
    ("giraffe","dʒəˈræf","长颈鹿","The giraffe has a very long neck."),
    ("pig","pɪɡ","猪","The pig likes eating."),
    ("cow","kaʊ","奶牛","The cow gives us milk."),
    ("sheep","ʃiːp","绵羊","The sheep is fluffy and white."),
    ("duck","dʌk","鸭子","The duck swims in the pond."),
    ("chicken","ˈtʃɪkɪn","鸡","The chicken lays eggs."),
    ("snake","sneɪk","蛇","The snake can be dangerous."),
    ("frog","frɔːɡ","青蛙","The frog catches flies."),
    ("horse","hɔːrs","马","The horse runs very fast."),
    ("bear","ber","熊","The bear likes honey."),
    ("wolf","wʊlf","狼","The wolf is a wild animal."),
    ("deer","dɪr","鹿","The deer runs very fast."),
    ("apple","ˈæpəl","苹果","An apple a day keeps the doctor away."),
    ("banana","bəˈnænə","香蕉","I like eating bananas."),
    ("orange","ˈɔːrɪndʒ","橙子","This orange is very juicy."),
    ("pear","per","梨","The pear is sweet and soft."),
    ("grape","ɡreɪp","葡萄","Grapes grow on vines."),
    ("watermelon","ˈwɔːtərmelən","西瓜","Watermelon is sweet in summer."),
    ("strawberry","ˈstrɔːbəri","草莓","Strawberries are red and sweet."),
    ("pineapple","ˈpaɪnæpəl","菠萝","Pineapple grows in tropical places."),
    ("peach","piːtʃ","桃子","The peach is soft and sweet."),
    ("lemon","ˈlemən","柠檬","Lemon is sour."),
    ("mango","ˈmæŋɡoʊ","芒果","Mango is a tropical fruit."),
    ("egg","eɡ","鸡蛋","I have an egg for breakfast."),
    ("bread","bred","面包","I eat bread every morning."),
    ("rice","raɪs","米饭","We eat rice with chopsticks."),
    ("noodles","ˈnuːdəlz","面条","I love Chinese noodles."),
    ("milk","mɪlk","牛奶","Children should drink more milk."),
    ("water","ˈwɔːtər","水","Drink more water every day."),
    ("juice","dʒuːs","果汁","I like orange juice."),
    ("tea","tiː","茶","Chinese tea is famous worldwide."),
    ("coffee","ˈkɔːfi","咖啡","Coffee is popular in the morning."),
    ("soup","suːp","汤","The soup is very delicious."),
    ("meat","miːt","肉","I eat meat every day."),
    ("chicken","ˈtʃɪkɪn","鸡肉","I like fried chicken very much."),
    ("beef","biːf","牛肉","Beef comes from cows."),
    ("pork","pɔːrk","猪肉","We often eat pork at home."),
    ("fish","fɪʃ","鱼肉","Fish is good for your health."),
    ("vegetables","ˈvedʒtəbəlz","蔬菜","Eat more vegetables every day."),
    ("tomato","təˈmeɪtoʊ","番茄","Tomatoes are red and round."),
    ("potato","pəˈteɪtoʊ","土豆","I like French fries."),
    ("carrot","ˈkærət","胡萝卜","Rabbits like carrots."),
    ("onion","ˈʌnjən","洋葱","The onion makes me cry."),
    ("garlic","ˈɡɑːrlɪk","大蒜","Garlic is good for your health."),
    ("cucumber","ˈkjuːkʌmbər","黄瓜","Cucumber is cool and refreshing."),
    ("eggplant","ˈeɡplænt","茄子","I don't like eggplant."),
    ("mushroom","ˈmʌʃrʊm","蘑菇","Mushrooms grow in dark places."),
    ("head","hed","头","I have a headache today."),
    ("face","feɪs","脸","Wash your face every morning."),
    ("eye","aɪ","眼睛","She has big bright eyes."),
    ("ear","ɪr","耳朵","I can hear with my ears."),
    ("nose","noʊz","鼻子","The dog has a wet nose."),
    ("mouth","maʊθ","嘴","Open your mouth wide."),
    ("tooth","tuːθ","牙齿","Brush your teeth twice a day."),
    ("hand","hænd","手","Raise your hand please."),
    ("finger","ˈfɪŋɡər","手指","I cut my finger."),
    ("foot","fʊt","脚","I hurt my foot."),
    ("feet","fiːt","脚（复数）","I stand on my feet."),
    ("leg","leɡ","腿","The table has four legs."),
    ("arm","ɑːrm","手臂","I broke my arm last year."),
    ("body","ˈbɑːdi","身体","Exercise is good for your body."),
    ("hair","her","头发","She has long black hair."),
    ("neck","nek","脖子","The giraffe has a long neck."),
    ("school","skuːl","学校","I go to school every day."),
    ("class","klæs","班级","We are in the same class."),
    ("classroom","ˈklæsruːm","教室","The classroom is very clean."),
    ("desk","desk","书桌","This is my desk."),
    ("chair","tʃer","椅子","Sit on the chair."),
    ("book","bʊk","书","I read a book every night."),
    ("pen","pen","钢笔","Please pass me a pen."),
    ("pencil","ˈpensəl","铅笔","I write with a pencil."),
    ("eraser","ɪˈreɪsər","橡皮擦","I need an eraser."),
    ("ruler","ˈruːlər","尺子","Use a ruler to draw a line."),
    ("bag","bæɡ","书包","I carry a bag to school."),
    ("ball","bɔːl","球","Let's play ball together."),
    ("football","ˈfʊtbɔːl","足球","I like playing football."),
    ("basketball","ˈbæskɪtbɔːl","篮球","Basketball is my favorite sport."),
    ("table","ˈteɪbəl","桌子","The book is on the table."),
    ("window","ˈwɪndoʊ","窗户","Open the window please."),
    ("door","dɔːr","门","Close the door behind you."),
    ("floor","flɔːr","地板","The floor is very clean."),
    ("wall","wɔːl","墙","There is a picture on the wall."),
    ("blackboard","ˈblækbɔːrd","黑板","The teacher writes on the blackboard."),
    ("clock","klɑːk","时钟","The clock on the wall says eight."),
    ("bus","bʌs","公共汽车","I take the bus to school."),
    ("car","kɑːr","小汽车","My father drives a car."),
    ("taxi","ˈtæksi","出租车","Let's take a taxi."),
    ("train","treɪn","火车","The train is very fast."),
    ("ship","ʃɪp","轮船","The ship sails on the sea."),
    ("plane","pleɪn","飞机","We fly to Beijing by plane."),
    ("bike","baɪk","自行车","I ride a bike to school."),
    ("boat","boʊt","小船","The boat is on the lake."),
    ("home","hoʊm","家","I am home now."),
    ("house","haʊs","房子","This is a big house."),
    ("room","ruːm","房间","This is my room."),
    ("kitchen","ˈkɪtʃɪn","厨房","Mother cooks in the kitchen."),
    ("bedroom","ˈbedruːm","卧室","I sleep in my bedroom."),
    ("bathroom","ˈbæθruːm","浴室","I take a shower in the bathroom."),
    ("garden","ˈɡɑːrdən","花园","There are beautiful flowers in the garden."),
    ("park","pɑːrk","公园","We often go to the park on weekends."),
    ("hospital","ˈhɑːspɪtəl","医院","The doctor works in a hospital."),
    ("shop","ʃɑːp","商店","I buy food at the shop."),
    ("supermarket","ˈsuːpərmɑːrkɪt","超市","The supermarket is very big."),
    ("restaurant","ˈrestərɑːnt","餐馆","We eat at a restaurant."),
    ("bank","bæŋk","银行","I go to the bank with my mother."),
    ("library","ˈlaɪbreri","图书馆","I borrow books from the library."),
    ("morning","ˈmɔːrnɪŋ","早上","Good morning to you!"),
    ("afternoon","ˌæftərˈnuːn","下午","Good afternoon! See you in the afternoon."),
    ("evening","ˈiːvnɪŋ","傍晚","Good evening!"),
    ("night","naɪt","夜晚","Good night! Sweet dreams."),
    ("today","təˈdeɪ","今天","What day is today?"),
    ("tomorrow","təˈmɑːroʊ","明天","See you tomorrow!"),
    ("yesterday","ˈjestərdeɪ","昨天","Yesterday was Monday."),
    ("Monday","ˈmʌndeɪ","星期一","I go to school on Monday."),
    ("Tuesday","ˈtuːzdeɪ","星期二","Tuesday comes after Monday."),
    ("Wednesday","ˈwenzdeɪ","星期三","Wednesday is the middle of the week."),
    ("Thursday","ˈθɜːrzdeɪ","星期四","Thursday is almost the weekend."),
    ("Friday","ˈfraɪdeɪ","星期五","Friday is the last school day."),
    ("Saturday","ˈsætərdeɪ","星期六","I play football on Saturday."),
    ("Sunday","ˈsʌndeɪ","星期日","Sunday is a holiday."),
    ("weekend","ˈwiːkend","周末","What do you do on the weekend?"),
    ("January","ˈdʒænjuːeri","一月","New Year's Day is in January."),
    ("February","ˈfebruːeri","二月","February has 28 or 29 days."),
    ("March","mɑːrtʃ","三月","March comes after February."),
    ("April","ˈeɪprəl","四月","April is the month of flowers."),
    ("May","meɪ","五月","May is a warm and beautiful month."),
    ("June","dʒuːn","六月","June is the start of summer."),
    ("July","dʒuˈlaɪ","七月","July is the hottest month."),
    ("August","ˈɔːɡəst","八月","August is very hot."),
    ("September","sepˈtembər","九月","School starts in September."),
    ("October","ɑːkˈtoʊbər","十月","October is the month of Halloween."),
    ("November","noʊˈvembər","十一月","November comes after October."),
    ("December","dɪˈsembər","十二月","Christmas is in December."),
    ("spring","sprɪŋ","春天","Flowers bloom in spring."),
    ("summer","ˈsʌmər","夏天","Summer is very hot."),
    ("autumn","ˈɔːtəm","秋天","Leaves fall in autumn."),
    ("winter","ˈwɪntər","冬天","Winter is cold and snowy."),
    ("weather","ˈweðər","天气","What is the weather like today?"),
    ("hot","hɑːt","热的","It is very hot in summer."),
    ("cold","koʊld","冷的","It is very cold in winter."),
    ("warm","wɔːrm","暖和的","Spring is warm and nice."),
    ("cool","kuːl","凉爽的","Evening is cool in autumn."),
    ("sunny","ˈsʌni","晴朗的","It is sunny today."),
    ("rainy","ˈreɪni","下雨的","It is rainy today. Take an umbrella."),
    ("cloudy","ˈklaʊdi","多云的","It is cloudy this morning."),
    ("snowy","ˈsnoʊi","下雪的","It is snowy in winter."),
    ("windy","ˈwɪndi","有风的","It is windy today."),
    ("big","bɪɡ","大的","The elephant is very big."),
    ("small","smɔːl","小的","The mouse is very small."),
    ("long","lɔːŋ","长的","The snake is very long."),
    ("short","ʃɔːrt","短的","My pencil is too short."),
    ("tall","tɔːl","高的","He is very tall."),
    ("young","jʌŋ","年轻的","The young man is strong."),
    ("old","oʊld","年老的","The old man walks slowly."),
    ("new","nuː","新的","I have a new bike."),
    ("old","oʊld","旧的","This is an old house."),
    ("good","ɡʊd","好的","This is a good book."),
    ("bad","bæd","坏的","Smoking is bad for health."),
    ("happy","ˈhæpi","快乐的","I am very happy today."),
    ("sad","sæd","悲伤的","The movie made me sad."),
    ("angry","ˈæŋɡri","生气的","He is very angry."),
    ("tired","ˈtaɪərd","累的","I am very tired today."),
    ("hungry","ˈhʌŋɡri","饿的","I am hungry. Can I have some food?"),
    ("thirsty","ˈθɜːrsti","渴的","I am thirsty. I need some water."),
    ("ill","ɪl","生病的","He is ill today. He can't come to school."),
    ("fine","faɪn","好的","I am fine, thank you."),
    ("nice","naɪs","友好的","She is a nice girl."),
    ("kind","kaɪnd","善良的","The teacher is very kind."),
    ("clever","ˈklevər","聪明的","The clever boy solved the problem."),
    ("cute","kjuːt","可爱的","The baby is very cute."),
    ("beautiful","ˈbjuːtɪfəl","美丽的","The flower is very beautiful."),
    ("pretty","ˈprɪti","漂亮的","She is very pretty."),
    ("funny","ˈfʌni","有趣的","The story is very funny."),
    ("busy","ˈbɪzi","忙的","I am busy with my homework."),
    ("free","friː","空闲的","I am free today."),
    ("easy","ˈiːzi","容易的","This question is very easy."),
    ("difficult","ˈdɪfɪkəlt","困难的","Math is difficult for me."),
    ("fast","fæst","快的","The train is very fast."),
    ("slow","sloʊ","慢的","The snail is very slow."),
    ("clean","kliːn","干净的","The classroom is very clean."),
    ("dirty","ˈdɜːrti","脏的","The floor is dirty."),
    ("light","laɪt","轻的","This bag is very light."),
    ("heavy","ˈhevi","重的","The box is very heavy."),
    ("loud","laʊd","大声的","The music is too loud."),
    ("quiet","ˈkwaɪət","安静的","The library is very quiet."),
    ("right","raɪt","正确的","Your answer is right."),
    ("wrong","rɔːŋ","错误的","That is the wrong answer."),
    ("left","left","左边的","Turn left at the corner."),
    ("right","raɪt","右边的","Turn right at the traffic light."),
    ("up","ʌp","向上","Look up at the sky."),
    ("down","daʊn","向下","Sit down please."),
    ("in","ɪn","在里面","The book is in the bag."),
    ("out","aʊt","在外面","Go out and play."),
    ("on","ɑːn","在...上面","The book is on the table."),
    ("under","ˈʌndər","在...下面","The cat is under the table."),
    ("near","nɪr","在...附近","The school is near my home."),
    ("far","fɑːr","远的","The park is not far from here."),
    ("here","hɪr","这里","Come here please."),
    ("there","ðer","那里","Go there and wait."),
    ("love","lʌv","爱","I love my family."),
    ("like","laɪk","喜欢","I like playing football."),
    ("hate","heɪt","讨厌","I hate getting up early."),
    ("want","wɑːnt","想要","I want an apple."),
    ("need","niːd","需要","I need some water."),
    ("eat","iːt","吃","I eat breakfast at seven."),
    ("drink","drɪŋk","喝","I drink water every day."),
    ("go","ɡoʊ","去","I go to school every day."),
    ("come","kʌm","来","Come here please."),
    ("run","rʌn","跑","I run very fast."),
    ("walk","wɔːk","走","I walk to school every day."),
    ("jump","dʒʌmp","跳","The frog can jump very high."),
    ("swim","swɪm","游泳","I can swim in summer."),
    ("fly","flaɪ","飞","Birds can fly."),
    ("play","pleɪ","玩","Children like to play games."),
    ("work","wɜːrk","工作","My father works in a hospital."),
    ("read","riːd","读","I read books every night."),
    ("write","raɪt","写","I write with a pen."),
    ("draw","drɔː","画画","I like to draw pictures."),
    ("sing","sɪŋ","唱歌","She can sing very well."),
    ("dance","dæns","跳舞","I like to dance."),
    ("sleep","sliːp","睡觉","I sleep eight hours every night."),
    ("wake","weɪk","醒来","I wake up at six every morning."),
    ("sit","sɪt","坐","Sit down please."),
    ("stand","stænd","站","Stand up, please."),
    ("open","ˈoʊpən","打开","Open the door please."),
    ("close","kloʊz","关闭","Close the window."),
    ("put","pʊt","放","Put the book on the table."),
    ("get","ɡet","得到","Get up! It's seven o'clock."),
    ("give","ɡɪv","给","Give me an apple, please."),
    ("take","teɪk","拿","Take this book to the library."),
    ("have","hæv","有","I have a new bag."),
    ("make","meɪk","做","My mother makes delicious food."),
    ("cook","kʊk","做饭","My mother cooks every day."),
    ("wash","wɑːʃ","洗","Wash your hands before eating."),
    ("clean","kliːn","打扫","Clean your room on weekends."),
    ("buy","baɪ","买","I want to buy a new pencil."),
    ("sell","sel","卖","The shop sells fruits."),
    ("bring","brɪŋ","带来","Bring your book tomorrow."),
    ("carry","ˈkæri","携带","The bag is heavy. I can't carry it."),
    ("use","juːz","使用","Use your head to think."),
    ("turn","tɜːrn","转","Turn left at the corner."),
    ("cut","kʌt","切","Cut the apple into two parts."),
    ("break","breɪk","打破","Don't break the cup."),
    ("hit","hɪt","打","Don't hit other children."),
    ("kick","kɪk","踢","Don't kick the ball in the house."),
    ("catch","kætʃ","抓","Catch the ball!"),
    ("throw","θroʊ","扔","Throw the ball to me."),
    ("help","help","帮助","Can you help me?"),
    ("show","ʃoʊ","展示","Show me your homework."),
    ("tell","tel","告诉","Tell me a story."),
    ("ask","æsk","问","Ask the teacher if you don't understand."),
    ("answer","ˈænsər","回答","Can you answer this question?"),
    ("think","θɪŋk","想","Think before you speak."),
    ("know","noʊ","知道","I know the answer."),
    ("learn","lɜːrn","学习","I learn English at school."),
    ("study","ˈstʌdi","学习","I study very hard."),
    ("remember","rɪˈmembər","记得","Remember to do your homework."),
    ("forget","fərˈɡet","忘记","Don't forget to lock the door."),
    ("find","faɪnd","找到","I can't find my pen."),
    ("lose","luːz","丢失","I lost my keys."),
    ("see","siː","看见","I can see a bird in the tree."),
    ("watch","wɑːtʃ","观看","I watch TV on weekends."),
    ("look","lʊk","看","Look at the blackboard."),
    ("hear","hɪr","听见","I can hear birds singing."),
    ("sound","saʊnd","听起来","That sounds great!"),
    ("smell","smel","闻","The flower smells sweet."),
    ("feel","fiːl","感觉","I feel happy today."),
    ("taste","teɪst","尝","The food tastes delicious."),
    ("am","æm","是（与I连用）","I am a student."),
    ("is","ɪz","是（单数）","She is a teacher."),
    ("are","ɑːr","是（复数）","We are in the same class."),
    ("was","wʌz","是（过去式单数）","She was sick yesterday."),
    ("were","wɜːr","是（过去式复数）","They were happy then."),
    ("do","duː","做","What do you do?"),
    ("does","dʌz","做（第三人称单数）","What does he do?"),
    ("did","dɪd","做（过去式）","What did you do yesterday?"),
    ("will","wɪl","将要","I will go to Beijing tomorrow."),
    ("can","kæn","能","I can swim very well."),
    ("must","mʌst","必须","You must finish your homework."),
    ("should","ʃʊd","应该","You should study hard."),
    ("may","meɪ","可能","You may go now."),
    ("this","ðɪs","这","This is my book."),
    ("that","ðæt","那","That is his desk."),
    ("these","ðiːz","这些","These are my friends."),
    ("those","ðoʊz","那些","Those are apple trees."),
    ("what","wʌt","什么","What is your name?"),
    ("which","wɪtʃ","哪一个","Which book is yours?"),
    ("who","huː","谁","Who is that man?"),
    ("whose","huːz","谁的","Whose bag is this?"),
    ("where","wer","在哪里","Where do you live?"),
    ("when","wen","什么时候","When is your birthday?"),
    ("why","waɪ","为什么","Why are you late?"),
    ("how","haʊ","怎样","How are you today?"),
    ("and","ænd","和","I like apples and bananas."),
    ("but","bʌt","但是","I like fish but I don't like meat."),
    ("or","ɔːr","或者","Do you like tea or coffee?"),
    ("so","soʊ","所以","I was late, so I missed the bus."),
    ("because","bɪˈkɔːz","因为","I am happy because I got a gift."),
    ("if","ɪf","如果","If it rains, I will stay at home."),
    ("then","ðen","那么","If you are tired, then rest."),
    ("very","ˈveri","非常","This book is very interesting."),
    ("really","ˈriːəli","真正地","I really like this song."),
    ("too","tuː","太","The water is too hot."),
    ("also","ˈɔːlsoʊ","也","I also like playing basketball."),
    ("quite","kwaɪt","相当","The book is quite good."),
    ("about","əˈbaʊt","关于","What is the book about?"),
    ("after","ˈæftər","在...之后","I will call you after school."),
    ("before","bɪˈfɔːr","在...之前","Brush your teeth before sleeping."),
    ("with","wɪð","和...一起","I go to school with my friend."),
    ("without","wɪˈðaʊt","没有","You can't see without eyes."),
    ("for","fɔːr","为了","This is a gift for you."),
    ("from","frʌm","从","Where are you from?"),
    ("of","ʌv","的","The color of the sky is blue."),
    ("to","tuː","到","Go to school every day."),
    ("at","æt","在","I am at home."),
    ("in","ɪn","在...里面","The book is in the bag."),
    ("on","ɑːn","在...上面","The picture is on the wall."),
    ("no","noʊ","不/没有","No, I don't like fish."),
    ("not","nɑːt","不","I am not hungry."),
    ("yes","jes","是","Yes, I like it very much."),
    ("please","pliːz","请","Please sit down."),
    ("thank","θæŋk","谢谢","Thank you very much."),
    ("sorry","ˈsɑːri","对不起","Sorry, I am late."),
    ("hello","həˈloʊ","你好","Hello, how are you?"),
    ("hi","haɪ","嗨","Hi, nice to meet you."),
    ("bye","baɪ","再见","Goodbye! See you tomorrow."),
    ("again","əˈɡen","再","Read it again."),
    ("now","naʊ","现在","I am busy now."),
    ("still","stɪl","仍然","He is still sleeping."),
    ("already","ɔːlˈredi","已经","I have already had breakfast."),
    ("ever","ˈevər","曾经","Have you ever been to Beijing?"),
    ("never","ˈnevər","从未","I have never been to Shanghai."),
    ("always","ˈɔːlweɪz","总是","The sun always rises in the east."),
    ("often","ˈɔːfən","经常","I often read books before bed."),
    ("sometimes","ˈsʌmtaɪmz","有时候","Sometimes I play football on weekends."),
    ("usually","ˈjuːʒuəli","通常","I usually get up at six."),
    ("much","mʌtʃ","很多","I like it very much."),
    ("many","ˈmeni","很多","There are many books in the library."),
    ("some","sʌm","一些","I have some good news."),
    ("any","ˈeni","任何","Do you have any questions?"),
    ("all","ɔːl","全部","All the students are here."),
    ("each","iːtʃ","每个","Each student has a desk."),
    ("both","boʊθ","两个都","Both of them are my friends."),
    ("other","ˈʌðər","其他的","Do you have any other questions?"),
    ("another","əˈnʌðər","另一个","I want another apple."),
    ("more","mɔːr","更多","I want more water."),
    ("most","moʊst","最多","Most students are here."),
    ("only","ˈoʊnli","只有","I have only one pencil."),
    ("just","dʒʌst","只是","I am just a student."),
    ("even","ˈiːvən","甚至","Even a child can do it."),
    ("than","ðæn","比","This book is better than that one."),
    ("as","æz","像...一样","She is as tall as her mother."),
    ("well","wel","好","She sings very well."),
    ("first","fɜːrst","第一","He came in first in the race."),
    ("last","læst","最后的","He was the last to leave."),
    ("next","nekst","下一个","See you next week."),
    ("time","taɪm","时间","What time is it?"),
    ("year","jɪr","年","This year I am in Grade Six."),
    ("month","mʌnθ","月","There are twelve months in a year."),
    ("week","wiːk","周","There are seven days in a week."),
    ("day","deɪ","天","What day is it today?"),
    ("hour","aʊr","小时","There are twenty-four hours in a day."),
    ("minute","ˈmɪnɪt","分钟","Wait a minute, please."),
    ("second","ˈsekənd","秒","The race only lasts ten seconds."),
    ("today","təˈdeɪ","今天","Today is Monday."),
    ("thing","θɪŋ","事情","I have many things to do."),
    ("something","ˈsʌmθɪŋ","某事","I have something to tell you."),
    ("nothing","ˈnʌθɪŋ","没什么","There is nothing in the box."),
    ("everything","ˈevrɪθɪŋ","一切","Everything is ready now."),
    ("people","ˈpiːpəl","人们","Many people like playing football."),
    ("world","wɜːrld","世界","The world is very big."),
    ("country","ˈkʌntri","国家","China is a beautiful country."),
    ("China","ˈtʃaɪnə","中国","Beijing is the capital of China."),
    ("America","əˈmerɪkə","美国","New York is a city in America."),
    ("England","ˈɪŋɡlənd","英国","London is the capital of England."),
    ("Japan","dʒəˈpæn","日本","Sakura blossoms are famous in Japan."),
    ("name","neɪm","名字","What is your name?"),
    ("age","eɪdʒ","年龄","What is your age?"),
    ("sex","seks","性别","What is your sex?"),
    ("birthday","ˈbɜːrθdeɪ","生日","Happy birthday to you!"),
    ("address","ˈædres","地址","What is your home address?"),
    ("number","ˈnʌmbə