#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate example sentences for high_school_3500.json vocabulary with Chinese translations."""

import json
import re
import random

# Sentence templates organized by meaning pattern
SENTENCE_TEMPLATES = {
    # 动词 (v.) patterns
    '放弃': ('Never abandon your dreams.', '永远不要放弃你的梦想。'),
    '抛弃': ('She would never abandon her friends.', '她永远不会抛弃她的朋友。'),
    '能力': ('She has the ability to speak five languages.', '她有说五种语言的能力。'),
    '能够': ('He is able to solve this problem.', '他能够解决这个问题。'),
    '放弃': ('You should never abandon your goals.', '你不应该放弃你的目标。'),
    '废除': ('The government decided to abolish the old law.', '政府决定废除旧法律。'),
    '废除': ('They want to abolish the death penalty.', '他们想废除死刑。'),
    '缺席': ('His absence was noticed by the teacher.', '老师注意到了他的缺席。'),
    '缺席': ('Her absence from the meeting was unexpected.', '她缺席会议出乎意料。'),
    '存在': ('Does ghosts really exist?', '鬼真的存在吗？'),
    'absent': ('He was absent from school yesterday.', '他昨天没来上学。'),
    'abolish': ('They voted to abolish the system.', '他们投票废除这个制度。'),
    'abnormal': ('The doctor found abnormal results.', '医生发现了异常结果。'),
    'abroad': ('She decided to study abroad.', '她决定出国学习。'),
    'abrupt': ('His abrupt decision surprised everyone.', '他突然的决定让所有人惊讶。'),
    'absorb': ('The sponge can absorb water easily.', '海绵能容易地吸水。'),
    'abstract': ('The concept is too abstract to understand.', '这个概念太抽象了难以理解。'),
    'abundant': ('China has abundant natural resources.', '中国有丰富的自然资源。'),
    'abuse': ('We should not abuse our power.', '我们不应该滥用权力。'),
    'academic': ('She has excellent academic achievements.', '她有出色的学业成绩。'),
    'accelerate': ('The car accelerated quickly.', '汽车快速加速。'),
    'accent': ('She speaks English with a British accent.', '她说话带英式口音。'),
    'accept': ('Please accept my sincere apology.', '请接受我真诚的道歉。'),
    'access': ('Students can access the library resources.', '学生可以使用图书馆资源。'),
    'accident': ('It was a terrible accident.', '那是一场可怕的事故。'),
    'accomplish': ('You can accomplish anything with hard work.', '努力工作你可以完成任何事。'),
    'according': ('According to the weather report, it will rain.', '根据天气预报，明天会下雨。'),
    'account': ('She opened a bank account.', '她开了个银行账户。'),
    'accurate': ('Please give an accurate answer.', '请给出准确的答案。'),
    'achieve': ('You can achieve your goals through effort.', '你可以通过努力实现目标。'),
    'acknowledge': ('I acknowledge your contribution.', '我承认你的贡献。'),
    'acquire': ('We should acquire new knowledge.', '我们应该获取新知识。'),
    'across': ('The store is across the street.', '商店在街对面。'),
    'act': ('We must act immediately.', '我们必须立即行动。'),
    'active': ('She is an active participant.', '她是一个积极的参与者。'),
    'activity': ('We have many extracurricular activities.', '我们有很多课外活动。'),
    'actual': ('What is the actual situation?', '实际情况是什么？'),
    'adapt': ('We must adapt to the new environment.', '我们必须适应新环境。'),
    'add': ('Please add more sugar.', '请加些糖。'),
    'adequate': ('The food is adequate for three people.', '这些食物够三个人吃。'),
    'adjust': ('You need to adjust your schedule.', '你需要调整你的时间表。'),
    'administration': ('The administration announced new policies.', '管理层宣布了新政策。'),
    'admire': ('I admire her courage.', '我钦佩她的勇气。'),
    'admit': ('He admitted his mistake.', '他承认了他的错误。'),
    'adopt': ('They decided to adopt a child.', '他们决定收养一个孩子。'),
    'adult': ('This movie is for adults only.', '这部电影仅限成人观看。'),
    'advance': ('The army advanced toward the city.', '军队向城市推进。'),
    'advantage': ('There are many advantages to living in the city.', '住在城市有很多好处。'),
    'adventure': ('Their adventure in the forest was exciting.', '他们在森林里的冒险很刺激。'),
    'advertise': ('Companies advertise their products on TV.', '公司在电视上做广告。'),
    'advice': ('Can you give me some advice?', '你能给我一些建议吗？'),
    'advise': ('I advise you to study hard.', '我建议你努力学习。'),
    'affair': ('It is a private affair.', '这是私事。'),
    'affect': ('The weather affects our mood.', '天气影响我们的心情。'),
    'afford': ('I cannot afford this expensive bag.', '我买不起这个昂贵的包。'),
    'afraid': ('Don\'t be afraid of failure.', '不要害怕失败。'),
    'after': ('I will call you after school.', '放学后我会打电话给你。'),
    'afternoon': ('Let\'s meet this afternoon.', '我们今天下午见吧。'),
    'again': ('Please try again.', '请再试一次。'),
    'against': ('We are against this plan.', '我们反对这个计划。'),
    'age': ('What is the average age of students?', '学生的平均年龄是多少？'),
    'agency': ('She works for a travel agency.', '她在旅行社工作。'),
    'agent': ('The insurance agent helped us.', '保险代理人帮助了我们。'),
    'agree': ('I agree with your opinion.', '我同意你的观点。'),
    'agreement': ('We reached an agreement finally.', '我们最终达成了协议。'),
    'ahead': ('Go straight ahead.', '一直往前走。'),
    'aid': ('They provided first aid to the victim.', '他们对受害者进行了急救。'),
    'aim': ('What is your aim in life?', '你的人生目标是什么？'),
    'air': ('Fresh air is good for health.', '新鲜空气对健康有益。'),
    'aircraft': ('The aircraft landed safely.', '飞机安全降落了。'),
    'airline': ('Which airline are you flying?', '你坐哪个航空公司的飞机？'),
    'airport': ('We arrived at the airport early.', '我们早早到了机场。'),
    'alarm': ('The alarm clock rang at six.', '闹钟六点响了。'),
    'album': ('This photo album is very beautiful.', '这本相册很漂亮。'),
    'alcohol': ('Alcohol is harmful to health.', '酒精对健康有害。'),
    'alike': ('The two sisters look very alike.', '两姐妹长得很像。'),
    'alive': ('Is she still alive?', '她还活着吗？'),
    'allow': ('Smoking is not allowed here.', '这里不允许吸烟。'),
    'almost': ('It is almost time for dinner.', '差不多该吃晚饭了。'),
    'alone': ('She lives alone in the apartment.', '她独自住在这公寓里。'),
    'along': ('Walk along this road.', '沿着这条路走。'),
    'aloud': ('Please read the text aloud.', '请大声朗读课文。'),
    'already': ('I have already finished my homework.', '我已经完成了作业。'),
    'also': ('She also likes music.', '她也喜欢音乐。'),
    'alter': ('You should alter your plan.', '你应该改变你的计划。'),
    'although': ('Although it was raining, we still went out.', '虽然下雨了，我们还是出去了。'),
    'altogether': ('There are ten people altogether.', '总共有十个人。'),
    'always': ('She always helps others.', '她总是帮助别人。'),
    'ambition': ('His ambition is to become a scientist.', '他的志向是成为科学家。'),
    'ambulance': ('Call an ambulance immediately!', '立即叫救护车！'),
    'among': ('She is among the best students.', '她是最优秀的学生之一。'),
    'amount': ('A large amount of money was stolen.', '大量金钱被偷了。'),
    'amuse': ('The clown amused the children.', '小丑逗乐了孩子们。'),
    'analyze': ('We need to analyze the data carefully.', '我们需要仔细分析数据。'),
    'ancient': ('China is an ancient civilization.', '中国是一个古老的文明。'),
    'anger': ('He could not control his anger.', '他无法控制自己的愤怒。'),
    'angle': ('Please measure the angle.', '请测量这个角度。'),
    'angry': ('She was very angry with me.', '她很生我的气。'),
    'animal': ('We should protect wild animals.', '我们应该保护野生动物。'),
    'announce': ('The government announced new policies.', '政府宣布了新政策。'),
    'annoy': ('His noise annoyed me.', '他的噪音让我烦恼。'),
    'annual': ('This is our annual meeting.', '这是我们的年度会议。'),
    'another': ('I have another question.', '我还有另一个问题。'),
    'answer': ('Can you answer this question?', '你能回答这个问题吗？'),
    'ant': ('The ant is a hardworking insect.', '蚂蚁是一种勤劳的昆虫。'),
    'anxious': ('I am anxious about the exam.', '我对考试感到焦虑。'),
    'any': ('Do you have any questions?', '你有什么问题吗？'),
    'anybody': ('Is anybody home?', '有人在吗？'),
    'anyone': ('Can anyone help me?', '有人能帮助我吗？'),
    'anything': ('You can take anything you like.', '你可以拿任何你喜欢的东西。'),
    'anyway': ('Anyway, let\'s continue.', '无论如何，我们继续吧。'),
    'anywhere': ('You can sit anywhere you like.', '你可以坐在任何你喜欢的地方。'),
    'apart': ('The two buildings are far apart.', '两栋建筑相距很远。'),
    'apologize': ('I want to apologize for my mistake.', '我想为我的错误道歉。'),
    'apparent': ('It is apparent that he is lying.', '很明显他在撒谎。'),
    'appeal': ('The new movie appeals to young people.', '这部电影吸引年轻人。'),
    'appear': ('The sun appears in the morning.', '太阳在早晨出现。'),
    'appetite': ('The walk gave me a good appetite.', '散步让我食欲大开。'),
    'apple': ('An apple a day keeps the doctor away.', '一天一苹果，医生远离我。'),
    'application': ('You need to fill out this application form.', '你需要填写这份申请表。'),
    'apply': ('I want to apply for this job.', '我想申请这份工作。'),
    'appoint': ('They appointed him as manager.', '他们任命他为经理。'),
    'appreciate': ('I appreciate your help.', '我感谢你的帮助。'),
    'approach': ('We need a new approach to this problem.', '我们需要解决这个问题的新方法。'),
    'appropriate': ('Wear appropriate clothing for the occasion.', '穿适合场合的衣服。'),
    'approve': ('The committee approved the proposal.', '委员会批准了这个提议。'),
    'approximate': ('What is the approximate number?', '大约是多少？'),
    'architect': ('The architect designed this beautiful building.', '建筑师设计了这座美丽的建筑。'),
    'architecture': ('She studies architecture at university.', '她在大学学建筑学。'),
    'area': ('What is the area of this room?', '这个房间的面积是多少？'),
    'argue': ('They argued about the plan.', '他们争论这个计划。'),
    'argument': ('They had an argument yesterday.', '他们昨天发生了争执。'),
    'arise': ('Problems arise every day.', '问题每天都会出现。'),
    'arm': ('She broke her arm in the accident.', '她在事故中摔断了手臂。'),
    'army': ('My brother joined the army.', '我哥哥参军了。'),
    'around': ('Look around you.', '看看你周围。'),
    'arrange': ('I need to arrange a meeting.', '我需要安排一个会议。'),
    'arrangement': ('We made arrangements for the trip.', '我们为旅行做了安排。'),
    'arrest': ('The police arrested the thief.', '警察逮捕了小偷。'),
    'arrival': ('We are waiting for his arrival.', '我们在等他的到来。'),
    'arrive': ('When will you arrive?', '你什么时候到？'),
    'arrow': ('The arrow hit the target.', '箭射中了目标。'),
    'art': ('She is interested in art.', '她对艺术感兴趣。'),
    'article': ('This is an interesting article.', '这是一篇有趣的文章。'),
    'artificial': ('This flower is artificial.', '这花是人造的。'),
    'artist': ('The artist painted a beautiful picture.', '艺术家画了一幅美丽的画。'),
    'artistic': ('She has artistic talent.', '她有艺术天赋。'),
    'ash': ('The cigarette ash fell on the carpet.', '烟灰落在地毯上。'),
    'ashamed': ('I am ashamed of my behavior.', '我为我的行为感到羞耻。'),
    'aside': ('Move the table aside.', '把桌子移到一边。'),
    'ask': ('May I ask a question?', '我可以问一个问题吗？'),
    'asleep': ('The baby is asleep.', '宝宝睡着了。'),
    'aspect': ('We should consider every aspect of the problem.', '我们应该考虑问题的每个方面。'),
    'assign': ('The teacher assigned homework.', '老师布置了作业。'),
    'assist': ('Can you assist me with this?', '你能帮我这个吗？'),
    'assistance': ('Thank you for your assistance.', '感谢你的帮助。'),
    'associate': ('Don\'t associate with bad people.', '不要和坏人交往。'),
    'association': ('She is a member of the teachers\' association.', '她是教师协会的成员。'),
    'assume': ('I assume you are coming.', '我假设你会来。'),
    'assure': ('I can assure you of our quality.', '我可以向你保证我们的质量。'),
    'astonish': ('The news astonished everyone.', '这个消息让所有人震惊。'),
    'astronaut': ('The astronaut went to space.', '宇航员去了太空。'),
    'at': ('I am at home.', '我在家。'),
    'athlete': ('The athlete broke the record.', '运动员打破了纪录。'),
    'athletic': ('She is very athletic.', '她很擅长运动。'),
    'atmosphere': ('The atmosphere in the room is comfortable.', '房间里的气氛很舒适。'),
    'atom': ('An atom is the smallest unit of matter.', '原子是物质的最小单位。'),
    'attach': ('Please attach the file.', '请附上文件。'),
    'attack': ('The enemy attacked at night.', '敌人在夜里发起攻击。'),
    'attempt': ('He attempted to climb the mountain.', '他尝试爬那座山。'),
    'attend': ('I will attend the meeting.', '我会参加会议。'),
    'attention': ('Pay attention to the teacher.', '注意听老师讲课。'),
    'attitude': ('She has a positive attitude.', '她有积极的态度。'),
    'attorney': ('The attorney defended his client.', '律师为他的当事人辩护。'),
    'attract': ('The movie attracts many audience.', '这部电影吸引了很多观众。'),
    'attraction': ('The main attraction is the beautiful scenery.', '主要景点是美丽的风景。'),
    'attractive': ('She is very attractive.', '她很有吸引力。'),
    'audience': ('The audience applauded loudly.', '观众大声鼓掌。'),
    'aunt': ('My aunt lives in Shanghai.', '我阿姨住在上海。'),
    'author': ('Who is the author of this book?', '这本书的作者是谁？'),
    'authority': ('You should consult the authorities.', '你应该咨询当局。'),
    'automatic': ('This is an automatic door.', '这是自动门。'),
    'available': ('Is this book available?', '这本书可借吗？'),
    'avenue': ('This is a famous avenue in New York.', '这是纽约著名的大道。'),
    'average': ('The average score is seventy.', '平均分是七十。'),
    'avoid': ('You should avoid making mistakes.', '你应该避免犯错误。'),
    'awake': ('The noise kept me awake.', '噪音让我睡不着。'),
    'award': ('She won the best actress award.', '她获得了最佳女演员奖。'),
    'aware': ('Are you aware of the danger?', '你意识到危险了吗？'),
    'away': ('Go away!', '走开！'),
    'awful': ('The weather is awful today.', '今天天气很糟糕。'),
    'awkward': ('This is an awkward situation.', '这是尴尬的情况。'),
    'baby': ('The baby is sleeping.', '宝宝在睡觉。'),
    'bachelor': ('He is still a bachelor.', '他还是单身。'),
    'back': ('Please sit back.', '请坐回去。'),
    'background': ('What is your background?', '你的背景是什么？'),
    'backward': ('The child walked backward.', '孩子向后走。'),
    'bacon': ('I would like some bacon and eggs.', '我想吃培根和鸡蛋。'),
    'bacteria': ('Bacteria can cause diseases.', '细菌能导致疾病。'),
    'bad': ('This is bad news.', '这是坏消息。'),
    'badly': ('He was badly injured.', '他受了重伤。'),
    'bag': ('This bag is very expensive.', '这个包很贵。'),
    'baggage': ('Please put your baggage in the car.', '请把你的行李放进车里。'),
    'bake': ('I like to bake cakes.', '我喜欢烤蛋糕。'),
    'balance': ('Keep the balance of nature.', '保持生态平衡。'),
    'ball': ('The ball hit the window.', '球打到了窗户。'),
    'balloon': ('The child held a balloon.', '孩子拿着一个气球。'),
    'ban': ('The government banned smoking in public.', '政府禁止在公共场所吸烟。'),
    'banana': ('I like bananas very much.', '我很喜欢香蕉。'),
    'band': ('The band played beautiful music.', '乐队演奏了优美的音乐。'),
    'bang': ('The door bang open.', '门砰地开了。'),
    'bank': ('I need to go to the bank.', '我需要去银行。'),
    'banner': ('The banner says "Welcome".', '横幅写着"欢迎"。'),
    'bar': ('Let\'s have a drink at the bar.', '我们在酒吧喝一杯吧。'),
    'barbecue': ('We had a barbecue last weekend.', '上周末我们吃了烧烤。'),
    'barrier': ('Language can be a barrier to communication.', '语言可能成为沟通的障碍。'),
    'base': ('The base of the mountain is very wide.', '山脚很宽。'),
    'baseball': ('Baseball is popular in America.', '棒球在美国很流行。'),
    'basic': ('This is a basic rule.', '这是基本规则。'),
    'basically': ('Basically, I agree with you.', '基本上，我同意你。'),
    'basin': ('Please wash your hands in the basin.', '请在水盆里洗手。'),
    'basis': ('On the basis of evidence, we decided.', '根据证据，我们做出了决定。'),
    'basket': ('There is a basket of fruits.', '有一篮水果。'),
    'basketball': ('We play basketball every Friday.', '我们每周五打篮球。'),
    'bath': ('I want to take a bath.', '我想洗个澡。'),
    'bathroom': ('Where is the bathroom?', '洗手间在哪里？'),
    'battery': ('The battery is dead.', '电池没电了。'),
    'battle': ('The battle lasted three days.', '战斗持续了三天。'),
    'bay': ('The ship sailed into the bay.', '船驶入海湾。'),
    'be': ('I want to be a doctor.', '我想当医生。'),
    'beach': ('Let\'s go to the beach this weekend.', '这周末我们去海滩吧。'),
    'beam': ('A beam of light came through the window.', '一道光束从窗户照进来。'),
    'bean': ('I like soy bean milk.', '我喜欢豆浆。'),
    'bear': ('The bear is a large animal.', '熊是一种大型动物。'),
    'beard': ('He has a long beard.', '他留着长胡子。'),
    'beast': ('The lion is the king of beasts.', '狮子是百兽之王。'),
    'beat': ('Who beat the record?', '谁打破了纪录？'),
    'beautiful': ('What a beautiful flower!', '多美的花啊！'),
    'beauty': ('Beauty is in the eye of the beholder.', '情人眼里出西施。'),
    'because': ('I study hard because I want to succeed.', '我努力学习因为我想成功。'),
    'become': ('She wants to become a teacher.', '她想成为一名老师。'),
    'bed': ('It is time for bed.', '该睡觉了。'),
    'bedroom': ('This is my bedroom.', '这是我的卧室。'),
    'bee': ('The bee makes honey.', '蜜蜂酿蜜。'),
    'beef': ('I prefer beef to pork.', '我更喜欢牛肉而不是猪肉。'),
    'beer': ('A glass of beer, please.', '请来一杯啤酒。'),
    'before': ('I had dinner before the movie.', '看电影前我吃了晚饭。'),
    'begin': ('Let\'s begin the meeting.', '让我们开始会议吧。'),
    'behalf': ('On behalf of my team, thank you.', '代表我的团队谢谢你。'),
    'behave': ('Children should behave well.', '孩子应该表现好。'),
    'behavior': ('His behavior surprised everyone.', '他的行为让所有人惊讶。'),
    'behind': ('The garden is behind the house.', '花园在房子后面。'),
    'being': ('The most important being is to be happy.', '最重要的是要快乐。'),
    'belief': ('It is my belief that he is innocent.', '我相信他是无辜的。'),
    'believe': ('I believe in you.', '我相信你。'),
    'bell': ('The bell rang.', '铃响了。'),
    'belong': ('This book belongs to me.', '这本书是我的。'),
    'below': ('The temperature is below zero.', '温度在零度以下。'),
    'belt': ('Please fasten your seat belt.', '请系好安全带。'),
    'bench': ('The bench is made of wood.', '长凳是木头做的。'),
    'bend': ('Can you bend your arm?', '你能弯曲手臂吗？'),
    'beneath': ('The cat is beneath the table.', '猫在桌子下面。'),
    'benefit': ('Exercise has many benefits.', '锻炼有很多好处。'),
    'bent': ('The tree is bent by the wind.', '树被风吹弯了。'),
    'beside': ('Sit beside me.', '坐在我旁边。'),
    'besides': ('Besides English, I also study French.', '除了英语，我还学法语。'),
    'best': ('She is the best student in class.', '她是班上最好的学生。'),
    'better': ('Practice makes better.', '熟能生巧。'),
    'between': ('Between you and me, he is wrong.', '你我之间说，他错了。'),
    'beyond': ('The sky is beyond the clouds.', '天空在云层之上。'),
    'bike': ('I ride my bike to school.', '我骑自行车去学校。'),
    'bill': ('Can I have the bill, please?', '请给我账单好吗？'),
    'billion': ('The company is worth 2 billion dollars.', '这家公司价值二十亿美元。'),
    'biology': ('She studies biology at university.', '她在大学学生物学。'),
    'bird': ('A bird is singing in the tree.', '一只鸟在树上唱歌。'),
    'birth': ('The baby weighed 3 kilograms at birth.', '宝宝出生时重三公斤。'),
    'birthday': ('Happy birthday to you!', '祝你生日快乐！'),
    'biscuit': ('I like biscuits with tea.', '我喜欢就着茶吃饼干。'),
    'bishop': ('The bishop gave a speech.', '主教发表了讲话。'),
    'bit': ('I have a bit of a headache.', '我有一点头疼。'),
    'bite': ('The dog might bite.', '狗可能会咬人。'),
    'bitter': ('This medicine is bitter.', '这药很苦。'),
    'black': ('The black cat is cute.', '黑猫很可爱。'),
    'blackboard': ('The teacher wrote on the blackboard.', '老师在黑板上写字。'),
    'blame': ('Don\'t blame others for your mistakes.', '不要把错误怪到别人身上。'),
    'blank': ('Please fill in the blank.', '请填写空白处。'),
    'blanket': ('The blanket is too thin.', '毯子太薄了。'),
    'blast': ('There was a loud blast.', '有一声巨响。'),
    'blaze': ('The fire blazed all night.', '火烧了一整夜。'),
    'bleed': ('His nose is bleeding.', '他鼻子在流血。'),
    'blend': ('Blend the ingredients together.', '把配料混合在一起。'),
    'bless': ('God bless you.', '上帝保佑你。'),
    'blind': ('The blind man needs help.', '盲人需要帮助。'),
    'block': ('There is a block in the pipe.', '管道里有堵塞物。'),
    'blood': ('Blood is red.', '血是红色的。'),
    'blossom': ('The apple blossom is beautiful.', '苹果花很美。'),
    'blow': ('The wind blows hard.', '风吹得很大。'),
    'blue': ('The sky is blue.', '天空是蓝色的。'),
    'blunt': ('This knife is blunt.', '这把刀钝了。'),
    'blush': ('She blushed when she saw him.', '她看到他时脸红了。'),
    'board': ('Please board the plane now.', '现在请登机。'),
    'boast': ('He boasted about his achievements.', '他吹嘘自己的成就。'),
    'boat': ('We rowed the boat across the lake.', '我们划船过湖。'),
    'body': ('Exercise is good for the body.', '锻炼对身体有益。'),
    'boil': ('Please boil some water.', '请烧些开水。'),
    'bold': ('He is a bold man.', '他是一个勇敢的人。'),
    'bolt': ('Please bolt the door.', '请把门闩上。'),
    'bomb': ('The bomb exploded.', '炸弹爆炸了。'),
    'bond': ('The bond between them is strong.', '他们之间的联系很牢固。'),
    'bone': ('The bone is broken.', '骨头断了。'),
    'bonus': ('The company gave us a year-end bonus.', '公司给了我们年终奖。'),
    'book': ('I want to book a room.', '我想预订一个房间。'),
    'boom': ('The economy is booming.', '经济正在蓬勃发展。'),
    'boost': ('We need to boost sales.', '我们需要促进销售。'),
    'boot': ('Put on your boots.', '穿上你的靴子。'),
    'border': ('The border between the two countries is long.', '两国边界很长。'),
    'bore': ('This movie bores me.', '这部电影让我感到无聊。'),
    'bored': ('I am bored with this work.', '我对这工作感到厌烦。'),
    'boring': ('The lecture was very boring.', '讲座很无聊。'),
    'born': ('He was born in 2000.', '他出生于2000年。'),
    'borrow': ('Can I borrow your pen?', '我能借你的笔吗？'),
    'boss': ('The boss is very strict.', '老板很严格。'),
    'both': ('Both of them are students.', '他们俩都是学生。'),
    'bother': ('Don\'t bother me now.', '现在别打扰我。'),
    'bottle': ('This bottle is empty.', '这瓶子是空的。'),
    'bottom': ('The bottom of the box is wet.', '箱子底部是湿的。'),
    'bounce': ('The ball bounces high.', '球弹得很高。'),
    'bound': ('The train is bound for Beijing.', '火车开往北京。'),
    'boundary': ('The boundary between the two fields is clear.', '两块地之间的边界很清楚。'),
    'bouquet': ('She received a bouquet of roses.', '她收到一束玫瑰花。'),
    'boutique': ('She runs a small boutique.', '她经营一家小时装店。'),
    'bow': ('Please bow to the teacher.', '请向老师鞠躬。'),
    'bowl': ('A bowl of rice, please.', '请来一碗米饭。'),
    'bowling': ('We went bowling last night.', '昨晚我们去打保龄球了。'),
    'box': ('This box is too heavy.', '这箱子太重了。'),
    'boxing': ('Boxing is a popular sport.', '拳击是一项受欢迎的运动。'),
    'boy': ('The boy is playing outside.', '男孩在外面玩。'),
    'boycott': ('They boycotted the meeting.', '他们抵制会议。'),
    'brain': ('The human brain is complex.', '人脑很复杂。'),
    'brake': ('Please apply the brake.', '请刹车。'),
    'branch': ('The bird sat on the branch.', '鸟停在树枝上。'),
    'brand': ('What brand of phone do you use?', '你用什么牌子的手机？'),
    'brandy': ('A glass of brandy, please.', '请来一杯白兰地。'),
    'brass': ('The brass band played well.', '铜管乐队演奏得很好。'),
    'brave': ('He is a brave soldier.', '他是一个勇敢的士兵。'),
    'bread': ('I eat bread for breakfast.', '我早餐吃面包。'),
    'break': ('Let\'s take a break.', '我们休息一下吧。'),
    'breakfast': ('I have breakfast at seven.', '我七点吃早餐。'),
    'breast': ('The bird feeds its young with its breast.', '鸟用胸口喂养幼鸟。'),
    'breath': ('He took a deep breath.', '他深吸了一口气。'),
    'breathe': ('Breathe deeply and relax.', '深呼吸放松。'),
    'breed': ('This dog breed is very popular.', '这个狗品种很受欢迎。'),
    'breeze': ('A gentle breeze is blowing.', '微风吹拂。'),
    'brick': ('The wall is made of bricks.', '墙是用砖砌成的。'),
    'bride': ('The bride looks beautiful.', '新娘看起来很美。'),
    'bridge': ('We crossed the bridge.', '我们过了桥。'),
    'brief': ('This is a brief introduction.', '这是简要介绍。'),
    'bright': ('The sun is bright today.', '今天阳光明媚。'),
    'brilliant': ('She is a brilliant student.', '她是一个出色的学生。'),
    'bring': ('Bring me a cup of tea, please.', '请给我端杯茶来。'),
    'broad': ('This is a broad street.', '这是一条宽阔的街道。'),
    'broadcast': ('The program will be broadcast tonight.', '节目今晚播出。'),
    'brochure': ('Please take this brochure.', '请拿这份小册子。'),
    'broken': ('The window is broken.', '窗户破了。'),
    'bronze': ('The statue is made of bronze.', '雕像是铜制的。'),
    'broom': ('Use the broom to sweep the floor.', '用扫帚扫地。'),
    'brother': ('My brother is older than me.', '我哥哥比我大。'),
    'brow': ('He wiped the sweat from his brow.', '他擦去额头的汗水。'),
    'brown': ('She has brown hair.', '她有棕色头发。'),
    'brush': ('I brush my teeth twice a day.', '我每天刷两次牙。'),
    'bubble': ('The child blew bubbles.', '孩子吹泡泡。'),
    'bucket': ('Please fetch a bucket of water.', '请打一桶水来。'),
    'budget': ('We need to make a budget.', '我们需要制定预算。'),
    'buffalo': ('The buffalo is a large animal.', '水牛是一种大型动物。'),
    'build': ('They are building a new school.', '他们正在建一所新学校。'),
    'building': ('This is a tall building.', '这是一栋高楼。'),
    'bullet': ('The bullet hit the target.', '子弹击中了目标。'),
    'bunch': ('She gave me a bunch of flowers.', '她给我一束花。'),
    'bundle': ('He carried a bundle of wood.', '他扛着一捆柴。'),
    'burden': ('The burden is too heavy.', '负担太重了。'),
    'bureau': ('The Federal Bureau of Investigation.', '联邦调查局。'),
    'burn': ('Be careful not to burn yourself.', '小心别烫到自己。'),
    'burst': ('The balloon burst.', '气球爆了。'),
    'bury': ('They buried the treasure.', '他们埋藏了宝藏。'),
    'bus': ('I take the bus to school.', '我乘公共汽车去学校。'),
    'bush': ('The bird is in the bush.', '鸟在灌木丛里。'),
    'business': ('Business is good this year.', '今年生意好。'),
    'busy': ('I am busy with my work.', '我忙着工作。'),
    'but': ('I want to go but I am tired.', '我想去，但我累了。'),
    'butter': ('I like butter on my bread.', '我喜欢在面包上涂黄油。'),
    'button': ('Please press the button.', '请按按钮。'),
    'buy': ('I want to buy a new computer.', '我想买一台新电脑。'),
    'buyer': ('The buyer is interested in the product.', '买家对产品感兴趣。'),
    'by': ('I go to school by bus.', '我乘公共汽车去学校。'),
    'bye': ('Good bye!', '再见！'),
    'cabbage': ('Cabbage is good for health.', '卷心菜对健康有益。'),
    'cabin': ('We stayed in a cabin in the mountains.', '我们住在山间的小屋里。'),
    'cabinet': ('The medicine is in the cabinet.', '药在柜子里。'),
    'cable': ('Please check the cable connection.', '请检查电缆连接。'),
    'cafe': ('We met at a cafe.', '我们在咖啡馆见面。'),
    'cage': ('The bird is in the cage.', '鸟在笼子里。'),
    'cake': ('I made a cake for her birthday.', '我为她的生日做了蛋糕。'),
    'calculate': ('Please calculate the total.', '请计算总数。'),
    'calendar': ('Circle the date on the calendar.', '在日历上圈出那个日期。'),
    'calf': ('The cow and her calf are in the field.', '母牛和它的小牛在田野里。'),
    'call': ('Please call me tonight.', '今晚请给我打电话。'),
    'calm': ('Stay calm and don\'t panic.', '保持冷静，不要惊慌。'),
    'camel': ('The camel can survive in the desert.', '骆驼能在沙漠中生存。'),
    'camera': ('I took a photo with my camera.', '我用相机拍了一张照片。'),
    'camp': ('We set up camp by the river.', '我们在河边扎营。'),
    'campaign': ('The campaign was successful.', '活动成功了。'),
    'campus': ('The campus is very beautiful.', '校园很美。'),
    'can': ('I can swim.', '我会游泳。'),
    'canal': ('The Suez Canal is famous.', '苏伊士运河很有名。'),
    'cancel': ('We had to cancel the meeting.', '我们不得不取消会议。'),
    'cancer': ('Cancer is a serious disease.', '癌症是一种严重的疾病。'),
    'candidate': ('He is a candidate for the position.', '他是这个职位的候选人。'),
    'candle': ('Light the candle.', '点燃蜡烛。'),
    'candy': ('The child likes candy.', '孩子喜欢糖果。'),
    'cannon': ('The cannon fired.', '大炮开火了。'),
    'canoe': ('We paddled the canoe.', '我们划独木舟。'),
    'cap': ('Please put on your cap.', '请戴上帽子。'),
    'capable': ('She is capable of doing this job.', '她有能力做这工作。'),
    'capacity': ('The stadium has a capacity of 50000.', '体育场可容纳五万人。'),
    'cape': ('The ship sailed around the cape.', '船绕过海角航行。'),
    'capital': ('Beijing is the capital of China.', '北京是中国的首都。'),
    'capsule': ('Take two capsules three times a day.', '每天三次，每次两粒胶囊。'),
    'captain': ('The captain led the team to victory.', '队长带领团队取得胜利。'),
    'captive': ('The captive was finally released.', '俘虏最终被释放了。'),
    'capture': ('The police captured the criminal.', '警察抓住了罪犯。'),
    'car': ('I bought a new car.', '我买了一辆新车。'),
    'carbon': ('Carbon is the basis of organic life.', '碳是有机生命的基础。'),
    'card': ('Please send a card to your friend.', '请给你的朋友寄张卡片。'),
    'care': ('Take care of yourself.', '照顾好自己。'),
    'career': ('She has a successful career.', '她事业有成。'),
    'careful': ('Be careful when you cross the street.', '过马路时要小心。'),
    'careless': ('His careless mistake cost us dearly.', '他的粗心大意让我们付出代价。'),
    'cargo': ('The ship carries cargo.', '船载货。'),
    'carpet': ('The carpet needs cleaning.', '地毯需要清洗。'),
    'carriage': ('The horse pulled the carriage.', '马拉着马车。'),
    'carrot': ('Rabbits like carrots.', '兔子喜欢胡萝卜。'),
    'carry': ('Can you carry this bag for me?', '你能帮我拿这个包吗？'),
    'cart': ('The horse pulled the cart.', '马拉着车。'),
    'cartoon': ('Children like watching cartoons.', '孩子喜欢看动画片。'),
    'carve': ('He carved a statue from wood.', '他用木头雕刻了一尊雕像。'),
    'case': ('This is a difficult case.', '这是一个困难的案例。'),
    'cash': ('I need to withdraw some cash.', '我需要取些现金。'),
    'cassette': ('I bought a cassette tape.', '我买了一盒磁带。'),
    'cast': ('The director cast him in the role.', '导演让他出演这个角色。'),
    'castle': ('The castle is very old.', '城堡很古老。'),
    'casual': ('This is just a casual meeting.', '这只是非正式会议。'),
    'catalog': ('Please check the catalog.', '请查看目录。'),
    'catch': ('Catch the ball!', '接住球！'),
    'category': ('This belongs to a different category.', '这属于不同的类别。'),
    'cater': ('The restaurant caters for weddings.', '这家餐厅承办婚礼宴席。'),
    'cathedral': ('The cathedral is under renovation.', '大教堂正在翻新。'),
    'cattle': ('They raise cattle for beef.', '他们养牛为了牛肉。'),
    'caught': ('The police caught the thief.', '警察抓住了小偷。'),
    'cause': ('What is the cause of the problem?', '问题的原因是什么？'),
    'caution': ('Use caution when handling chemicals.', '处理化学品时要小心。'),
    'cautious': ('She is cautious about spending money.', '她对花钱很谨慎。'),
    'cave': ('The cave is very dark.', '洞穴很黑。'),
    'cease': ('The company will cease operations.', '公司将停止运营。'),
    'ceiling': ('The ceiling is very high.', '天花板很高。'),
    'celebrate': ('Let\'s celebrate your success!', '让我们庆祝你的成功！'),
    'celebration': ('The celebration lasted all night.', '庆祝活动持续了一整夜。'),
    'cell': ('The human body is made of cells.', '人体由细胞组成。'),
    'cellar': ('The wine is stored in the cellar.', '酒存在地下室里。'),
    'cement': ('The road is made of cement.', '路由水泥制成。'),
    'census': ('The government conducts a census.', '政府进行人口普查。'),
    'cent': ('I don\'t have a cent.', '我一分钱都没有。'),
    'center': ('The shopping center is crowded.', '购物中心很拥挤。'),
    'centimeter': ('It is 20 centimeters long.', '它有二十厘米长。'),
    'central': ('Beijing is the central city of China.', '北京是中国的中心城市。'),
    'century': ('We are in the 21st century.', '我们在21世纪。'),
    'ceremony': ('The opening ceremony was impressive.', '开幕式令人印象深刻。'),
    'certain': ('I am certain of his success.', '我确信他会成功。'),
    'certainly': ('Certainly, I will help you.', '当然，我会帮助你。'),
    'chain': ('The chain is broken.', '链条断了。'),
    'chair': ('Please sit on the chair.', '请坐在椅子上。'),
    'chairman': ('The chairman called the meeting.', '主席召开了会议。'),
    'chalk': ('The teacher wrote with chalk.', '老师用粉笔写字。'),
    'challenge': ('This is a big challenge.', '这是一个巨大的挑战。'),
    'chamber': ('The rocket chamber exploded.', '火箭燃烧室爆炸了。'),
    'champion': ('He is the world champion.', '他是世界冠军。'),
    'chance': ('It is a good chance to learn.', '这是学习的好机会。'),
    'change': ('Change your attitude.', '改变你的态度。'),
    'channel': ('What channel is the game on?', '比赛在哪个频道？'),
    'chaos': ('There was chaos after the earthquake.', '地震后一片混乱。'),
    'chapter': ('Read the first chapter.', '读第一章。'),
    'character': ('She has a strong character.', '她性格坚强。'),
    'characteristic': ('What are the characteristics of this plant?', '这种植物有什么特征？'),
    'charge': ('Who is in charge here?', '这里谁负责？'),
    'charity': ('She donated money to charity.', '她向慈善机构捐了钱。'),
    'charm': ('The village has its own charm.', '村庄有它独特的魅力。'),
    'chart': ('Please look at the chart.', '请看图表。'),
    'chase': ('The dog chases the cat.', '狗追猫。'),
    'chat': ('Let\'s chat online.', '我们网聊吧。'),
    'cheap': ('This is very cheap.', '这很便宜。'),
    'cheat': ('Don\'t cheat in the exam.', '考试不要作弊。'),
    'check': ('Please check your email.', '请检查你的邮件。'),
    'cheek': ('Her cheek is red.', '她的脸颊红红的。'),
    'cheer': ('The crowd cheered for the team.', '观众为队伍欢呼。'),
    'cheerful': ('She is always cheerful.', '她总是很开朗。'),
    'cheese': ('I like cheese pizza.', '我喜欢芝士披萨。'),
    'chef': ('The chef prepared a delicious meal.', '厨师准备了一顿美食。'),
    'chemical': ('Keep chemicals away from children.', '让化学品远离儿童。'),
    'chemist': ('The chemist prepared the medicine.', '药剂师配了药。'),
    'chemistry': ('I like chemistry.', '我喜欢化学。'),
    'cheque': ('Please pay by cheque.', '请用支票付款。'),
    'cherry': ('Cherries are sweet.', '樱桃很甜。'),
    'chess': ('Do you play chess?', '你下棋吗？'),
    'chest': ('I have a pain in my chest.', '我胸口疼。'),
    'chew': ('Chew your food well.', '好好咀嚼食物。'),
    'chicken': ('I like fried chicken.', '我喜欢炸鸡。'),
    'chief': ('The chief made the decision.', '首领做了决定。'),
    'child': ('The child is playing.', '孩子在玩。'),
    'childhood': ('I spent my childhood in the countryside.', '我在乡下度过童年。'),
    'children': ('The children are reading books.', '孩子们在读书。'),
    'chill': ('The wind made me chill.', '风吹得我冷。'),
    'chimney': ('Smoke comes from the chimney.', '烟从烟囱里出来。'),
    'chin': ('Rest your chin on your hand.', '把你的下巴放在手上。'),
    'chip': ('The computer chip is very advanced.', '电脑芯片非常先进。'),
    'chocolate': ('I love chocolate.', '我喜欢巧克力。'),
    'choice': ('This is a difficult choice.', '这是困难的选择。'),
    'choose': ('Choose your friends carefully.', '谨慎选择朋友。'),
    'chop': ('Chop the wood into pieces.', '把木头劈成碎片。'),
    'chord': ('The chord sounds beautiful.', '和弦听起来很美。'),
    'chore': ('Doing housework is a daily chore.', '做家务是每天的杂事。'),
    'chorus': ('The chorus of the song is catchy.', '歌曲的副歌很动听。'),
    'Christian': ('She is a Christian.', '她是基督教徒。'),
    'Christmas': ('Merry Christmas!', '圣诞快乐！'),
    'chronic': ('He has a chronic disease.', '他有慢性病。'),
    'church': ('We go to church on Sunday.', '我们周日去教堂。'),
    'cigarette': ('Smoking cigarette is harmful.', '吸烟有害健康。'),
    'circle': ('Draw a circle.', '画一个圆。'),
    'circuit': ('The racing circuit is very long.', '赛道很长。'),
    'circular': ('This is a circular table.', '这是一张圆桌。'),
    'circumstance': ('Under the circumstances, we did our best.', '在这种环境下，我们尽力了。'),
    'circus': ('The children enjoyed the circus.', '孩子们喜欢马戏团。'),
    'cite': ('Let me cite an example.', '让我举一个例子。'),
    'citizen': ('She is a Chinese citizen.', '她是中国公民。'),
    'city': ('Beijing is a big city.', '北京是一个大城市。'),
    'civil': ('This is a civil matter.', '这是民事问题。'),
    'civilian': ('The civilian was injured.', '平民受伤了。'),
    'civilization': ('Chinese civilization is one of the oldest.', '中华文明是最古老的文明之一。'),
    'claim': ('I claim that this is true.', '我断言这是真的。'),
    'clam': ('Clam is a type of seafood.', '蛤蜊是一种海鲜。'),
    'clap': ('Clap your hands.', '拍手。'),
    'clarify': ('Can you clarify your statement?', '你能澄清你的陈述吗？'),
    'clash': ('There was a clash between the two teams.', '两队之间发生了冲突。'),
    'clasp': ('The clasp of the necklace is broken.', '项链的搭扣坏了。'),
    'class': ('What class are you in?', '你在哪个班？'),
    'classic': ('This is a classic novel.', '这是一本经典小说。'),
    'classical': ('I like classical music.', '我喜欢古典音乐。'),
    'classify': ('We can classify animals into groups.', '我们可以把动物分类。'),
    'clause': ('This clause is important.', '这一条款很重要。'),
    'claw': ('The cat has sharp claws.', '猫有锋利的爪子。'),
    'clay': ('The pot is made of clay.', '罐子是陶土做的。'),
    'clean': ('Please keep the room clean.', '请保持房间干净。'),
    'clear': ('The sky is clear today.', '今天天空晴朗。'),
    'clerk': ('The clerk helped me.', '职员帮助了我。'),
    'clever': ('He is a clever student.', '他是一个聪明的学生。'),
    'click': ('Click the button to continue.', '点击按钮继续。'),
    'client': ('The lawyer met his client.', '律师见了他的当事人。'),
    'cliff': ('The cliff is very high.', '悬崖很高。'),
    'climate': ('The climate in the south is warm.', '南方气候温暖。'),
    'climb': ('Let\'s climb the mountain.', '我们爬山吧。'),
    'clinic': ('The clinic is open on Saturday.', '诊所周六开门。'),
    'clip': ('Please clip the papers together.', '请把文件夹在一起。'),
    'cloak': ('She wore a cloak.', '她披着斗篷。'),
    'clock': ('The clock struck twelve.', '时钟敲了十二下。'),
    'clone': ('Scientists cloned a sheep.', '科学家克隆了一只羊。'),
    'close': ('Please close the door.', '请关门。'),
    'cloth': ('This cloth feels soft.', '这布料摸起来柔软。'),
    'clothe': ('They clothe the children in warm clothes.', '他们给孩子穿暖和的衣服。'),
    'clothes': ('I need to wash my clothes.', '我需要洗衣服。'),
    'clothing': ('The store sells winter clothing.', '这家店卖冬季服装。'),
    'cloud': ('There are many clouds in the sky.', '天空中有很多云。'),
    'cloudy': ('It is cloudy today.', '今天多云。'),
    'clown': ('The clown made the children laugh.', '小丑逗得孩子们大笑。'),
    'club': ('She joined the English club.', '她加入了英语俱乐部。'),
    'clue': ('Do you have any clues?', '你有什么线索吗？'),
    'clumsy': ('He is clumsy with his hands.', '他手很笨拙。'),
    'cluster': ('A cluster of grapes.', '一串葡萄。'),
    'clutch': ('She clutched the rope tightly.', '她紧紧抓住绳子。'),
    'clutch': ('The car has a clutch pedal.', '汽车有离合器踏板。'),
    'coach': ('The coach trained the team.', '教练训练队伍。'),
    'coal': ('Coal is used for fuel.', '煤用作燃料。'),
    'coarse': ('This cloth is coarse.', '这布料很粗糙。'),
    'coast': ('We drove along the coast.', '我们沿着海岸开车。'),
    'coat': ('Put on your coat.', '穿上外套。'),
    'coconut': ('Coconut milk is delicious.', '椰奶很好喝。'),
    'code': ('What is the postal code?', '邮政编码是什么？'),
    'coffee': ('I want a cup of coffee.', '我想喝杯咖啡。'),
    'coffin': ('The coffin was carried by six men.', '棺材由六个人抬着。'),
    'coil': ('The snake coiled around the branch.', '蛇盘绕在树枝上。'),
    'coin': ('He flipped a coin.', '他抛硬币。'),
    'coincide': ('Our birthdays coincide.', '我们生日在同一天。'),
    'coincidence': ('What a coincidence!', '真巧！'),
    'cold': ('I have a cold.', '我感冒了。'),
    'collapse': ('The building collapsed.', '建筑倒塌了。'),
    'collar': ('The dog has a red collar.', '狗戴着红色项圈。'),
    'colleague': ('My colleague helped me.', '我的同事帮助了我。'),
    'collect': ('I collect stamps.', '我收集邮票。'),
    'collection': ('The museum has a large collection.', '博物馆有大量收藏。'),
    'collective': ('It is a collective decision.', '这是集体决定。'),
    'college': ('She goes to college next year.', '她明年上大学。'),
    'colon': ('Use a colon in the sentence.', '在句子里使用冒号。'),
    'colony': ('Australia was once a British colony.', '澳大利亚曾是英国殖民地。'),
    'color': ('What is your favorite color?', '你最喜欢什么颜色？'),
    'colorful': ('The garden is colorful.', '花园五彩缤纷。'),
    'column': ('There is a column in the room.', '房间里有一根柱子。'),
    'comb': ('She used a comb to fix her hair.', '她用梳子整理头发。'),
    'combat': ('They fought in combat.', '他们参加战斗。'),
    'combine': ('Combine the ingredients.', '混合配料。'),
    'come': ('Come here, please.', '请到这里来。'),
    'comedy': ('I like watching comedy.', '我喜欢看喜剧。'),
    'comet': ('A comet passed the Earth.', '一颗彗星掠过地球。'),
    'comfort': ('The mother comforted her child.', '母亲安慰她的孩子。'),
    'comfortable': ('This chair is comfortable.', '这把椅子很舒服。'),
    'command': ('The captain gave the command.', '船长下了命令。'),
    'commander': ('The commander ordered an attack.', '指挥官下令进攻。'),
    'commemorate': ('We commemorate the heroes.', '我们纪念英雄。'),
    'commence': ('The meeting will commence at nine.', '会议将在九点开始。'),
    'comment': ('Can you make a comment?', '你能评论一下吗？'),
    'commerce': ('E-commerce is growing fast.', '电子商务发展很快。'),
    'commercial': ('It is a commercial advertisement.', '这是商业广告。'),
    'commission': ('He gets a commission on sales.', '他得到销售佣金。'),
    'commit': ('You must commit to the plan.', '你必须承诺执行这个计划。'),
    'commitment': ('It requires a big commitment.', '这需要很大的承诺。'),
    'committee': ('The committee made a decision.', '委员会做出了决定。'),
    'common': ('It is a common mistake.', '这是常见错误。'),
    'communicate': ('We communicate by email.', '我们通过邮件沟通。'),
    'communication': ('Communication is important.', '沟通很重要。'),
    'communism': ('He believes in communism.', '他信仰共产主义。'),
    'communist': ('She is a communist party member.', '她是共产党员。'),
    'community': ('The community is very friendly.', '社区很友好。'),
    'compact': ('The compact disc is popular.', '光盘很流行。'),
    'companion': ('She is my companion.', '她是我的同伴。'),
    'company': ('I work for a big company.', '我在一家大公司工作。'),
    'compare': ('Compare the two options.', '比较这两个选项。'),
    'comparison': ('There is no comparison.', '无法比较。'),
    'compel': ('Law compels us to pay taxes.', '法律迫使我们纳税。'),
    'compete': ('We compete with each other.', '我们互相竞争。'),
    'competition': ('The competition is fierce.', '竞争很激烈。'),
    'compile': ('We compile the data.', '我们汇编数据。'),
    'complain': ('I want to complain.', '我想投诉。'),
    'complaint': ('We received many complaints.', '我们收到很多投诉。'),
    'complete': ('Complete the form.', '填写表格。'),
    'completely': ('I completely agree.', '我完全同意。'),
    'complex': ('Life is complex.', '生活是复杂的。'),
    'complexion': ('She has a fair complexion.', '她肤色白皙。'),
    'complicate': ('Don\'t complicate the problem.', '不要把问题复杂化。'),
    'compose': ('She composes music.', '她作曲。'),
    'composer': ('The composer is famous.', '作曲家很有名。'),
    'compound': ('Water is a compound of hydrogen and oxygen.', '水是氢氧化合物。'),
    'comprehension': ('Reading comprehension is important.', '阅读理解很重要。'),
    'comprehensive': ('This is a comprehensive guide.', '这是一本综合指南。'),
    'compress': ('Compress the file before sending.', '发送前压缩文件。'),
    'computer': ('The computer is fast.', '电脑很快。'),
    'concentrate': ('Please concentrate on your work.', '请专心工作。'),
    'concentration': ('I need more concentration.', '我需要更专注。'),
    'concept': ('The concept is difficult.', '这个概念很难。'),
    'concern': ('I am concerned about the environment.', '我关心环境。'),
    'concerned': ('He is concerned for her safety.', '他担心她的安全。'),
    'concerning': ('I have no information concerning this.', '我没有关于此事的任何信息。'),
    'concert': ('We went to a concert.', '我们去听了音乐会。'),
    'conclude': ('Let me conclude my speech.', '让我总结发言。'),
    'conclusion': ('What is your conclusion?', '你的结论是什么？'),
    'concrete': ('The wall is made of concrete.', '墙是混凝土做的。'),
    'condemn': ('We condemn violence.', '我们谴责暴力。'),
    'condition': ('What is your condition?', '你的状况如何？'),
    'conduct': ('The experiment was conducted well.', '实验进行得很好。'),
    'conductor': ('The train conductor checked the tickets.', '列车员检查了车票。'),
    'cone': ('An ice cream cone, please.', '请来一个蛋筒冰淇淋。'),
    'conference': ('The conference starts tomorrow.', '会议明天开始。'),
    'confess': ('I must confess my mistake.', '我必须承认我的错误。'),
    'confidence': ('I have confidence in you.', '我对你有信心。'),
    'confident': ('She is confident about her future.', '她对自己的未来有信心。'),
    'confine': ('Please confine your remarks to the topic.', '请使你的评论紧扣主题。'),
    'confirm': ('Please confirm your attendance.', '请确认你能出席。'),
    'conflict': ('There is a conflict between them.', '他们之间有冲突。'),
    'confront': ('We must confront the problem.', '我们必须面对问题。'),
    'confuse': ('The question confused me.', '问题把我弄糊涂了。'),
    'confused': ('I am confused.', '我很困惑。'),
    'confusing': ('The instructions are confusing.', '说明令人困惑。'),
    'confusion': ('There is confusion about the plan.', '对计划有疑惑。'),
    'congratulate': ('I want to congratulate you.', '我想祝贺你。'),
    'congratulations': ('Congratulations on your success!', '祝贺你的成功！'),
    'congress': ('The Congress passed the law.', '国会通过了法律。'),
    'conjunction': ('We use "and" as a conjunction.', '我们用"and"作为连词。'),
    'connect': ('Connect the two points.', '连接两点。'),
    'connection': ('There is a poor connection.', '连接很差。'),
    'conscience': ('Follow your conscience.', '凭良心行事。'),
    'conscious': ('She is conscious of her mistake.', '她意识到自己的错误。'),
    'consciousness': ('He lost consciousness.', '他失去了意识。'),
    'consent': ('She gave her consent.', '她同意了。'),
    'consequence': ('You must face the consequence.', '你必须面对后果。'),
    'consequently': ('Consequently, we changed our plan.', '因此，我们改变了计划。'),
    'conservation': ('Wildlife conservation is important.', '野生动物保护很重要。'),
    'conservative': ('He has conservative views.', '他有保守的观点。'),
    'consider': ('Please consider my proposal.', '请考虑我的提议。'),
    'considerable': ('It requires considerable effort.', '这需要相当大的努力。'),
    'considerate': ('She is very considerate.', '她很体贴。'),
    'consideration': ('Your safety is our consideration.', '你的安全是我们的考虑。'),
    'consist': ('The team consists of ten members.', '团队由十名成员组成。'),
    'consistent': ('Be consistent in your work.', '保持工作一致。'),
    'console': ('I tried to console her.', '我试图安慰她。'),
    'constant': ('There is constant rain.', '雨一直下。'),
    'constitution': ('The constitution guarantees rights.', '宪法保障权利。'),
    'construct': ('They construct a new building.', '他们建造新楼。'),
    'construction': ('The construction takes time.', '建设需要时间。'),
    'consult': ('I will consult my lawyer.', '我会咨询我的律师。'),
    'consultant': ('She is a business consultant.', '她是商业顾问。'),
    'consume': ('This car consumes less fuel.', '这车消耗更少的燃料。'),
    'consumer': ('The consumer is always right.', '消费者总是对的。'),
    'consumption': ('Lower fuel consumption.', '降低燃料消耗。'),
    'contact': ('Let\'s keep in contact.', '让我们保持联系。'),
    'contain': ('This bottle contains water.', '这瓶子装着水。'),
    'contemporary': ('This is contemporary art.', '这是当代艺术。'),
    'contempt': ('I feel contempt for him.', '我鄙视他。'),
    'content': ('Are you content with your life?', '你对你的生活满意吗？'),
    'contest': ('She won the singing contest.', '她赢得了歌唱比赛。'),
    'context': ('Understand the context.', '理解上下文。'),
    'continent': ('Africa is a continent.', '非洲是一个大洲。'),
    'continue': ('Continue your work.', '继续你的工作。'),
    'continuous': ('There is continuous rain.', '雨一直下。'),
    'contract': ('Sign the contract.', '签合同。'),
    'contradict': ('Don\'t contradict your boss.', '不要反驳你的老板。'),
    'contrary': ('On the contrary, I disagree.', '相反，我不同意。'),
    'contrast': ('Compare and contrast.', '比较和对比。'),
    'contribute': ('Contribute to the charity.', '向慈善机构捐款。'),
    'contribution': ('Your contribution is appreciated.', '感谢你的贡献。'),
    'control': ('Control your temper.', '控制你的脾气。'),
    'controversial': ('It is a controversial topic.', '这是一个有争议的话题。'),
    'controversy': ('There is a controversy about it.', '对此有争议。'),
    'convenience': ('We value convenience.', '我们重视便利。'),
    'convenient': ('Is it convenient for you?', '你方便吗？'),
    'convention': ('The convention lasted three days.', '会议持续三天。'),
    'conversation': ('We had a conversation.', '我们进行了对话。'),
    'converse': ('He can converse in English.', '他能用英语交谈。'),
    'convert': ('Convert the file to PDF.', '把文件转换成PDF。'),
    'convey': ('Words convey meaning.', '文字表达意思。'),
    'convince': ('I convinced him to come.', '我说服他来。'),
    'cook': ('I like to cook.', '我喜欢烹饪。'),
    'cooker': ('The pressure cooker is useful.', '高压锅很有用。'),
    'cookie': ('The cookie tastes good.', '饼干味道很好。'),
    'cool': ('The weather is cool today.', '今天天气凉爽。'),
    'cooperate': ('We need to cooperate.', '我们需要合作。'),
    'cooperation': ('International cooperation is needed.', '需要国际合作。'),
    'cope': ('I cannot cope with the stress.', '我无法应对压力。'),
    'copper': ('This pipe is made of copper.', '这管子是铜做的。'),
    'copy': ('Please copy the file.', '请复制文件。'),
    'coral': ('Coral reefs are beautiful.', '珊瑚礁很美。'),
    'cord': ('The vocal cords vibrated.', '声带振动。'),
    'core': ('The core of the Earth is hot.', '地球核心是热的。'),
    'cork': ('Pull out the cork.', '拔出软木塞。'),
    'corn': ('The corn is sweet.', '玉米很甜。'),
    'corner': ('The shop is on the corner.', '商店在拐角处。'),
    'corporate': ('Corporate culture matters.', '公司文化很重要。'),
    'corporation': ('He works for a large corporation.', '他在大公司工作。'),
    'correct': ('Please correct my mistakes.', '请纠正我的错误。'),
    'correspond': ('We correspond by letters.', '我们通过信件通信。'),
    'correspondence': ('Business correspondence is formal.', '商业函件是正式的。'),
    'corridor': ('Walk down the corridor.', '沿着走廊走。'),
    'corrupt': ('The corrupt official was arrested.', '腐败官员被捕了。'),
    'corruption': ('Corruption is illegal.', '腐败是违法的。'),
    'cosmetics': ('She sells cosmetics.', '她卖化妆品。'),
    'cost': ('The cost is too high.', '成本太高了。'),
    'costly': ('It is a costly mistake.', '这是个代价高昂的错误。'),
    'costume': ('She wore a traditional costume.', '她穿了传统服装。'),
    'cosy': ('The room is warm and cosy.', '房间温暖又舒适。'),
    'cottage': ('We stayed in a cottage by the sea.', '我们住在海边的小屋里。'),
    'cotton': ('Cotton is comfortable.', '棉花很舒适。'),
    'cough': ('I have a bad cough.', '我咳嗽得厉害。'),
    'council': ('The council made a decision.', '议会做了决定。'),
    'counsel': ('He counseled me to wait.', '他建议我等待。'),
    'counselor': ('She is a school counselor.', '她是学校辅导员。'),
    'count': ('Count from one to ten.', '从一数到十。'),
    'counter': ('Please go to the counter.', '请到柜台去。'),
    'country': ('China is a beautiful country.', '中国是一个美丽的国家。'),
    'countryside': ('The countryside is peaceful.', '乡村很宁静。'),
    'county': ('They live in the same county.', '他们住在同一个县。'),
    'couple': ('A couple of friends.', '几个朋友。'),
    'courage': ('He showed great courage.', '他表现出极大的勇气。'),
    'course': ('Of course, I will help you.', '当然，我会帮助你。'),
    'court': ('The case went to court.', '案件上了法庭。'),
    'courtesy': ('Please show courtesy.', '请礼貌待人。'),
    'cousin': ('My cousin lives in Beijing.', '我表姐住在北京。'),
    'cover': ('Cover the pot.', '盖上锅。'),
    'coverage': ('The news coverage was extensive.', '新闻报道很广泛。'),
    'cow': ('The cow gives milk.', '奶牛产奶。'),
    'coward': ('Don\'t be a coward.', '不要当懦夫。'),
    'cozy': ('It is a cozy room.', '这是一个舒适的房间。'),
    'crack': ('There is a crack in the wall.', '墙上有裂缝。'),
    'cracker': ('Eat some crackers.', '吃些饼干。'),
    'cradle': ('The cradle is for babies.', '摇篮是给婴儿的。'),
    'craft': ('She learned the craft of pottery.', '她学会了陶艺。'),
    'crash': ('The car crashed into the tree.', '汽车撞到了树。'),
    'crawl': ('The baby is learning to crawl.', '宝宝正在学爬。'),
    'crazy': ('He is crazy about football.', '他痴迷足球。'),
    'cream': ('Ice cream is sweet.', '冰淇淋很甜。'),
    'create': ('We create new things.', '我们创造新事物。'),
    'creation': ('The creation of the world.', '世界的创造。'),
    'creative': ('She is very creative.', '她很有创造力。'),
    'creator': ('The creator of the universe.', '宇宙的创造者。'),
    'creature': ('Sea creatures are diverse.', '海洋生物多种多样。'),
    'credit': ('Give credit where it is due.', '该表扬的要表扬。'),
    'creek': ('The boat sailed up the creek.', '船驶入小溪。'),
    'creep': ('The cat crept toward the mouse.', '猫悄悄地向老鼠逼近。'),
    'crew': ('The crew worked hard.', '船员努力工作。'),
    'cricket': ('Cricket is popular in England.', '板球在英国很流行。'),
    'crime': ('Crime is a serious problem.', '犯罪是严重问题。'),
    'criminal': ('The criminal was caught.', '罪犯被捕了。'),
    'crisis': ('We faced a financial crisis.', '我们面临金融危机。'),
    'critic': ('The film critic gave a good review.', '影评人给了好评。'),
    'critical': ('It is a critical moment.', '这是关键时刻。'),
    'criticism': ('I accept your criticism.', '我接受你的批评。'),
    'criticize': ('Don\'t criticize others.', '不要批评别人。'),
    'crooked': ('The picture is crooked.', '画歪了。'),
    'crop': ('The crop was good this year.', '今年收成好。'),
    'cross': ('Cross the street carefully.', '小心过马路。'),
    'crouch': ('He crouched behind the wall.', '他蹲在墙后。'),
    'crowd': ('There is a crowd of people.', '有一群人。'),
    'crown': ('The queen wore a crown.', '女王戴着王冠。'),
    'crucial': ('It is a crucial decision.', '这是关键决定。'),
    'crude': ('The crude oil is unprocessed.', '原油是未加工的。'),
    'cruel': ('Don\'t be cruel to animals.', '不要对动物残忍。'),
    'cruise': ('We went on a cruise.', '我们坐游轮旅游了。'),
    'crumble': ('The wall started to crumble.', '墙开始崩塌。'),
    'crush': ('Don\'t crush the box.', '别压坏盒子。'),
    'crust': ('The crust of the bread is crispy.', '面包皮很脆。'),
    'cubic': ('This is a cubic meter.', '这是一立方米。'),
    'cucumber': ('Cucumber is refreshing.', '黄瓜清爽可口。'),
    'cultivate': ('Cultivate good habits.', '培养好习惯。'),
    'cultural': ('We should respect cultural differences.', '我们应该尊重文化差异。'),
    'culture': ('Chinese culture is rich.', '中国文化很丰富。'),
    'cumulative': ('It has a cumulative effect.', '它有累积效应。'),
    'cup': ('A cup of tea, please.', '请来一杯茶。'),
    'cupboard': ('The cupboards are full.', '橱柜满了。'),
    'cure': ('The doctor cured my illness.', '医生治好了我的病。'),
    'curiosity': ('Curiosity killed the cat.', '好奇心害死猫。'),
    'curious': ('I am curious about this.', '我对这个很好奇。'),
    'curl': ('Her hair curls naturally.', '她的头发自然卷曲。'),
    'currency': ('What is the currency of Japan?', '日本的货币是什么？'),
    'current': ('The current is strong.', '水流很急。'),
    'currently': ('I am currently busy.', '我目前很忙。'),
    'curriculum': ('The school has a new curriculum.', '学校有新课程。'),
    'curse': ('The witch put a curse on him.', '女巫对他下了诅咒。'),
    'curtain': ('Close the curtain.', '拉上窗帘。'),
    'curve': ('Draw a curve line.', '画一条曲线。'),
    'cushion': ('The sofa has soft cushions.', '沙发有软垫。'),
    'custom': ('It is a local custom.', '这是当地风俗。'),
    'customer': ('The customer is always right.', '顾客总是对的。'),
    'customs': ('We went through customs.', '我们通过了海关。'),
    'cycle': ('The bicycle is a popular vehicle.', '自行车是受欢迎的交通工具。'),
}

def get_sentence(word, meaning):
    """Get sentence and translation based on word or meaning."""
    word_lower = word.lower().strip()

    # Try exact word match
    if word_lower in SENTENCE_TEMPLATES:
        return SENTENCE_TEMPLATES[word_lower]

    # Try meaning keywords
    for key, value in SENTENCE_TEMPLATES.items():
        if key in meaning or meaning in key:
            return value

    # Try part of speech patterns
    pos_match = re.match(r'^(n\.|v\.|adj\.|adv\.|art\.|pron\.|conj\.|prep\.)', meaning.strip())
    if pos_match:
        pos = pos_match.group(1)
        # Generate based on part of speech
        if pos == 'n.':
            return (f"The {word} is important.", f"{word}很重要。")
        elif pos == 'v.':
            return (f"We must {word} carefully.", f"我们必须谨慎地{get_chinese_verb(word)}。")
        elif pos == 'adj.':
            return (f"This is {word}.", f"这是{get_chinese_adj(word, meaning)}。")

    # Default fallback
    return (f"The word '{word}' is commonly used.", f"'{word}'是一个常用词。")

def get_chinese_verb(word):
    """Get Chinese translation of verb."""
    # Simple mapping for common verbs
    verbs = {
        'abandon': '放弃', 'abolish': '废除', 'absorb': '吸收', 'accept': '接受',
        'access': '访问', 'accident': '遭遇', 'accomplish': '完成', 'achieve': '实现',
        'acknowledge': '承认', 'acquire': '获得', 'adapt': '适应', 'add': '添加',
        'adjust': '调整', 'admire': '钦佩', 'admit': '承认', 'adopt': '采用',
        'advise': '建议', 'affect': '影响', 'afford': '负担得起', 'agree': '同意',
        'allow': '允许', 'analyze': '分析', 'announce': '宣布', 'answer': '回答',
        'apologize': '道歉', 'apply': '申请', 'appoint': '任命', 'appreciate': '感激',
        'approach': '接近', 'approve': '批准', 'argue': '争论', 'arrange': '安排',
        'arrest': '逮捕', 'arrive': '到达', 'ask': '问', 'assemble': '组装',
        'assess': '评估', 'assist': '协助', 'assume': '假设', 'assure': '保证',
        'attach': '附加', 'attack': '攻击', 'attempt': '尝试', 'attend': '参加',
        'avoid': '避免', 'awake': '醒来', 'award': '奖励', 'be': '是',
        'bear': '承受', 'beat': '打败', 'become': '成为', 'beg': '请求',
        'begin': '开始', 'behave': '表现', 'believe': '相信', 'belong': '属于',
        'bend': '弯曲', 'benefit': '有益于', 'betray': '背叛', 'bid': '出价',
        'bind': '绑', 'bite': '咬', 'blame': '责备', 'bless': '祝福',
        'block': '阻止', 'blow': '吹', 'boil': '煮沸', 'borrow': '借',
        'bother': '打扰', 'bounce': '弹跳', 'bow': '鞠躬', 'break': '打破',
        'breathe': '呼吸', 'bring': '带来', 'broadcast': '广播', 'brush': '刷',
        'build': '建造', 'burn': '燃烧', 'burst': '爆发', 'bury': '埋葬',
        'buy': '买', 'calculate': '计算', 'call': '打电话', 'calm': '使平静',
        'cancel': '取消', 'capture': '捕获', 'care': '关心', 'carry': '携带',
        'carve': '雕刻', 'case': '情况', 'cast': '投射', 'catch': '抓住',
        'cause': '导致', 'cease': '停止', 'celebrate': '庆祝', 'challenge': '挑战',
        'change': '改变', 'charge': '收费', 'chase': '追逐', 'chat': '聊天',
        'check': '检查', 'cheer': '欢呼', 'chew': '咀嚼', 'choose': '选择',
        'circle': '环绕', 'claim': '声称', 'clap': '拍手', 'clarify': '澄清',
        'clash': '冲突', 'classify': '分类', 'clean': '清洁', 'clear': '清除',
        'climb': '爬', 'cling': '坚持', 'close': '关闭', 'coach': '训练',
        'coast': ('海岸', '沿岸'), 'code': '编码', 'collapse': '倒塌',
        'combine': '结合', 'come': '来', 'comfort': '安慰', 'command': '命令',
        'comment': '评论', 'communicate': '沟通', 'compare': '比较', 'compete': '竞争',
        'complain': '抱怨', 'complete': '完成', 'compose': '组成', 'compute': '计算',
        'concentrate': '集中', 'conclude': '结论', 'condemn': '谴责', 'conduct': 'conduct',
        'confess': '坦白', 'confuse': '使困惑', 'congratulate': '祝贺', 'connect': '连接',
        'consider': '考虑', 'consist': '由...组成', 'consult': '咨询', 'consume': '消费',
        'contact': '联系', 'contain': '包含', 'continue': '继续', 'contract': '签合同',
        'contrast': '对比', 'contribute': '贡献', 'control': '控制', 'convert': '转换',
        'convince': '说服', 'cook': '烹饪', 'cool': '冷却', 'cooperate': '合作',
        'cope': '应对', 'copy': '复制', 'correct': '纠正', 'cost': '花费',
        'count': '数', 'couple': '连接', 'cover': '覆盖', 'crack': '裂开',
        'crash': '撞碎', 'crawl': '爬行', 'create': '创造', 'criticize': '批评',
        'cross': '穿过', 'crush': '压碎', 'cry': '哭', 'cultivate': '培养',
        'cure': '治愈', 'curl': '卷曲', 'cut': '切', 'cycle': '循环',
    }
    return verbs.get(word.lower(), word)

def get_chinese_adj(word, meaning):
    """Get Chinese translation of adjective."""
    adj_mapping = {
        'abnormal': '异常的', 'absent': '缺席的', 'absolute': '绝对的',
        'abundant': '丰富的', 'academic': '学术的', 'acceptable': '可接受的',
        'accurate': '准确的', 'active': '积极的', 'acute': '敏锐的',
        'adequate': '足够的', 'adjacent': '邻近的', 'adjustable': '可调整的',
        'admirable': '令人钦佩的', 'advanced': '先进的', 'adverse': '不利的',
        'aggressive': '侵略性的', 'agreeable': '令人愉快的', 'alert': '警觉的',
        'alike': '相似的', 'alive': '活着的', 'alone': '孤独的',
        'ambitious': '有雄心的', 'amusing': '有趣的', 'ancient': '古代的',
        'anxious': '焦虑的', 'apparent': '明显的', 'appealing': '吸引人的',
        'appropriate': '适当的', 'approximate': '大约的', 'artificial': '人造的',
        'artistic': '艺术的', 'ashamed': '羞耻的', 'astonishing': '令人惊讶的',
        'attached': '附着的', 'attractive': '吸引人的', 'authentic': '真实的',
        'automatic': '自动的', 'available': '可用的', 'awful': '糟糕的',
        'awkward': '尴尬的', 'balanced': '平衡的', 'bare': '赤裸的',
        'base': '基础的', 'beautiful': '美丽的', 'beneficial': '有益的',
        'bitter': '苦涩的', 'blank': '空白的', 'blind': '盲的',
        'bold': '大胆的', 'boring': '无聊的', 'borrowed': '借来的',
        'brave': '勇敢的', 'brief': '简短的', 'bright': '明亮的',
        'brilliant': '出色的', 'broad': '宽阔的', 'broken': '破碎的',
        'bumpy': '颠簸的', 'capable': '有能力的', 'careful': '仔细的',
        'careless': '粗心的', 'casual': '随意的', 'cautious': '谨慎的',
        'central': '中心的', 'certain': '确定的', 'challenging': '有挑战性的',
        'characteristic': '特有的', 'cheap': '便宜的', 'cheerful': '快乐的',
        'chief': '主要的', 'circular': '圆形的', 'civil': '公民的',
        'civilian': '民用的', 'classic': '经典的', 'clean': '干净的',
        'clear': '清晰的', 'clever': '聪明的', 'clinical': '临床的',
        'close': '接近的', 'closed': '关闭的', 'cloudy': '多云的',
        'coarse': '粗糙的', 'cold': '冷的', 'collective': '集体的',
        'colonial': '殖民的', 'colorful': '五彩缤纷的', 'comfortable': '舒适的',
        'commercial': '商业的', 'common': '常见的', 'compact': '紧凑的',
        'comparable': '可比较的', 'comparative': '比较的', 'compatible': '兼容的',
        'competitive': '竞争的', 'complete': '完整的', 'complex': '复杂的',
        'complicated': '复杂的', 'comprehensive': '全面的', 'compulsory': '义务的',
        'concentrated': '集中的', 'concrete': '具体的', 'confident': '自信的',
        'confidential': '机密的', 'confused': '困惑的', 'conscious': '有意识的',
        'conservative': '保守的', 'consistent': '一致的', 'constant': '恒定的',
        'constructive': '建设性的', 'contemporary': '当代的', 'content': '满意的',
        'contrary': '相反的', 'controllable': '可控制的', 'controversial': '有争议的',
        'conventional': '常规的', 'convincing': '令人信服的', 'cool': '凉爽的',
        'cooperative': '合作的', 'correct': '正确的', 'cosmic': '宇宙的',
        'courageous': '勇敢的', 'courteous': '有礼貌的', 'crazy': '疯狂的',
        'creative': '创造性的', 'credible': '可信的', 'critical': '关键的',
        'crucial': '至关重要的', 'crude': '粗糙的', 'cruel': '残忍的',
        'cultural': '文化的', 'cunning': '狡猾的', 'curious': '好奇的',
        'current': '当前的', 'customary': '习惯的', 'cute': '可爱的',
        'daily': '每日的', 'dairy': '乳制品的', 'damaging': '有害的',
        'damp': '潮湿的', 'dangerous': '危险的', 'daring': '大胆的',
        'dead': '死的', 'deadly': '致命的', 'deaf': '聋的',
        'dear': '亲爱的', 'decent': '体面的', 'decisive': '决定性的',
        'decline': '下降', 'decorative': '装饰性的', 'deep': '深的',
        'defeated': '被打败的', 'defensive': '防御性的', 'definite': '明确的',
        'deliberate': '故意的', 'delicate': '精致的', 'delicious': '美味的',
        'delighted': '高兴的', 'demanding': '要求高的', 'democratic': '民主的',
        'dense': '密集的', 'departed': '过去的', 'dependent': '依赖的',
        'depressed': '沮丧的', 'determined': '坚决的', 'devoted': '忠诚的',
        'diplomatic': '外交的', 'direct': '直接的', 'dirty': '脏的',
        'disadvantaged': '贫困的', 'disappointed': '失望的', 'disappointing': '令人失望的',
        'disastrous': '灾难性的', 'discarded': '被丢弃的', 'discharged': '已出院的',
        'discontent': '不满的', 'discouraging': '令人沮丧的', 'discriminatory': '歧视性的',
        'diseased': '有病的', 'disguised': '伪装的', 'disgusting': '令人厌恶的',
        'dishonest': '不诚实的', 'disloyal': '不忠诚的', 'dismal': '沉闷的',
        'dismissive': '轻视的', 'disorderly': '混乱的', 'disparate': '截然不同的',
        'displaced': '流离失所的', 'displayed': '显示的', 'disposable': '一次性的',
        'dissatisfied': '不满意的', 'distant': '遥远的', 'distinct': '明显的',
        'distinguished': '卓越的', 'distracted': '分心的', 'disturbing': '令人不安的',
        'diverse': '多样的', 'divided': '分裂的', 'divine': '神圣的',
        'dominant': '占优势的', 'doubtful': '可疑的', 'dramatic': '戏剧性的',
        'dreadful': '可怕的', 'driving': '驱动的', 'drunk': '醉的',
        'dry': '干的', 'dual': '双重的', 'due': '到期的',
        'dull': '无聊的', 'dummy': '虚拟的', 'durable': '耐用的',
        'dynamic': '动态的', 'eager': '热切的', 'earnest': '认真的',
        'eastern': '东方的', 'easy': '容易的', 'economic': '经济的',
        'educated': '受过教育的', 'eerie': '怪异的', 'effective': '有效的',
        'efficient': '高效的', 'elaborate': '精心制作的', 'elated': '得意洋洋的',
        'elderly': '年老的', 'elegant': '优雅的', 'elementary': '基本的',
        'elevated': '升高的', 'embarrassed': '尴尬的', 'embarrassing': '令人尴尬的',
        'embattled': '困境的', 'emblematic': '象征性的', 'emergency': '紧急的',
        'emotional': '情绪化的', 'emphasis': '强调的', 'empirical': '经验的',
        'empty': '空的', 'enchanting': '迷人的', 'encouraging': '令人鼓舞的',
        'endless': '无尽的', 'energetic': '精力充沛的', 'enforced': '强制的',
        'engaged': '已订婚的', 'engaging': '吸引人的', 'enhanced': '增强的',
        'enormous': '巨大的', 'enthusiastic': '热情的', 'entire': '整个的',
        'entitled': '有资格的', 'envious': '嫉妒的', 'epidemic': '流行的',
        'equal': '平等的', 'equivalent': '等价的', 'erratic': '不稳定的',
        'essential': '必要的', 'ethical': '伦理的', 'eventual': '最终的',
        'everyday': '日常的', 'evident': '明显的', 'evolutionary': '进化的',
        'exact': '精确的', 'exaggerated': '夸大的', 'exasperated': '恼怒的',
        'excessive': '过度的', 'exchanged': '交换的', 'excited': '兴奋的',
        'exciting': '令人兴奋的', 'exclusive': '独有的', 'excusable': '可原谅的',
        'exhausted': '疲惫的', 'exhaustive': '全面的', 'exotic': '异国的',
        'expanded': '扩展的', 'expensive': '昂贵的', 'experienced': '有经验的',
        'experimental': '实验性的', 'explicit': '明确的', 'explosive': '爆炸性的',
        'exposed': '暴露的', 'express': '快速的', 'extended': '延伸的',
        'extensive': '广泛的', 'external': '外部的', 'extra': '额外的',
        'extraordinary': '非凡的', 'extreme': '极端的', 'faint': '微弱的',
        'faithful': '忠诚的', 'false': '错误的', 'familiar': '熟悉的',
        'famous': '著名的', 'fancy': '花哨的', 'fantastic': '极好的',
        'fatal': '致命的', 'favorable': '有利的', 'fearful': '可怕的',
        'feasible': '可行的', 'february': '二月的', 'federal': '联邦的',
        'fellow': '同伴的', 'felt': 'felt', 'female': '女性的',
        'fierce': '凶猛的', 'final': '最终的', 'financial': '金融的',
        'fine': '好的', 'firm': '坚定的', 'fixed': '固定的',
        'flagrant': '臭名昭著的', 'flawed': '有缺陷的', 'flexible': '灵活的',
        'fluent': '流利的', 'focal': '焦点的', 'fond': '喜欢的',
        'foolish': '愚蠢的', 'forced': '被迫的', 'forceful': '强有力的',
        'forecast': '预测的', 'foreign': '外国的', 'forensic': '法医的',
        'formal': '正式的', 'former': '前者的', 'formidable': '令人敬畏的',
        'forthcoming': '即将到来的', 'fortune': '财富', 'forward': '向前的',
        'fragile': '脆弱的', 'fragrant': '香的', 'frank': '坦率的',
        'frantic': '疯狂的', 'free': '自由的', 'fresh': '新鲜的',
        'friendly': '友好的', 'front': '前面的', 'frozen': '冻结的',
        'full': '满的', 'full-time': '全时的', 'functional': '功能的',
        'fundamental': '基本的', 'furious': '愤怒的', 'future': '未来的',
        'fuzzy': '模糊的', 'gaining': '获得的', 'generous': '慷慨的',
        'genetic': '遗传的', 'genuine': '真正的', 'geographic': '地理的',
        'gifted': '有天赋的', 'gigantic': '巨大的', 'given': '给定的',
        'glad': '高兴的', 'global': '全球的', 'glorious': '光荣的',
        'golden': '金色的', 'governing': '统治的', 'graceful': '优雅的',
        'gradual': '渐进的', 'grand': '宏伟的', 'grateful': '感激的',
        'greedy': '贪婪的', 'green': '绿色的', 'grievous': '严重的',
        'grim': '严峻的', 'gross': '总的', 'guilty': '有罪的',
        'handicapped': '残疾的', 'handsome': '英俊的', 'handy': '方便的',
        'hanging': '悬挂的', 'hapless': '不幸的', 'happy': '快乐的',
        'hard': '硬的', 'harmful': '有害的', 'harmless': '无害的',
        'harsh': '刺耳的', 'hazardous': '危险的', 'head': '头的',
        'healing': '愈合的', 'healthy': '健康的', 'heavenly': '天堂般的',
        'heavy': '重的', 'heli': '螺旋', 'helpful': '有帮助的',
        'helpless': '无助的', 'hidden': '隐藏的', 'high': '高的',
        'high-level': '高级的', 'historic': '有历史意义的', 'historical': '历史的',
        'hollow': '空的', 'holy': '神圣的', 'homeless': '无家可归的',
        'homework': '家庭作业', 'homogeneous': '同质的', 'honest': '诚实的',
        'honorable': '可敬的', 'hopeful': '有希望的', 'hopeless': '绝望的',
        'horizontal': '水平的', 'horrible': '可怕的', 'horrific': '可怕的',
        'hostile': '敌对的', 'hot': '热的', 'hour': '小时的',
        'household': '家庭的', 'housing': '住房的', 'human': '人类的',
        'humble': '谦逊的', 'humorous': '幽默的', 'hungry': '饥饿的',
        'hurried': '仓促的', 'hurt': '受伤的', 'hygienic': '卫生的',
        'ideal': '理想的', 'identical': '相同的', 'ideological': '意识形态的',
        'ignorant': '无知的', 'ill': '生病的', 'illegal': '非法的',
        'imaginative': '富有想象力的', 'immediate': '立即的', 'immense': '巨大的',
        'immune': '免疫的', 'impact': '影响', 'impartial': '公正的',
        'impending': '即将发生的', 'implicit': '含蓄的', 'impolite': '不礼貌的',
        'important': '重要的', 'impossible': '不可能的', 'impressed': '印象深刻的',
        'impressive': '令人印象深刻的', 'improper': '不适当的', 'inadequate': '不足的',
        'inappropriate': '不适当的', 'incapable': '无能力的', 'incentive': '激励的',
        'incoming': '到来的', 'incomparable': '无可比拟的', 'incompatible': '不兼容的',
        'incomplete': '不完整的', 'incorrect': '不正确的', 'incredible': '难以置信的',
        'indefinite': '无限的', 'independent': '独立的', 'indifferent': '漠不关心的',
        'indirect': '间接的', 'individual': '个人的', 'indoor': '室内的',
        'industrial': '工业的', 'inevitable': '不可避免的', 'influential': '有影响力的',
        'informal': '非正式的', 'informed': '了解情况的', 'inherent': '固有的',
        'initial': '最初的', 'innovative': '创新的', 'innocent': '无辜的',
        'innumerable': '无数的', 'insect': '昆虫', 'insensitive': '不敏感的',
        'inseparable': '不可分割的', 'insidious': '阴险的', 'insignificant': '无关紧要的',
        'insistent': '坚持的', 'insolent': '无礼的', 'inspired': '受启发的',
        'instant': '立即的', 'instinctive': '本能的', 'institutional': '制度的',
        'instructive': '有教育意义的', 'insulting': '侮辱的', 'intact': '完整的',
        'integral': '完整的', 'intellectual': '智力的', 'intelligent': '聪明的',
        'intense': '强烈的', 'intensive': '加强的', 'intentional': '故意的',
        'interactive': '互动的', 'intercontinental': '洲际的', 'interesting': '有趣的',
        'interior': '内部的', 'intermediate': '中间的', 'internal': '内部的',
        'international': '国际的', 'interpersonal': '人际的', 'interrupted': '中断的',
        'intimate': '亲密的', 'intrepid': '无畏的', 'intrinsic': '固有的',
        'invalid': '无效的', 'invaluable': '无价的', 'inventive': '有创意的',
        'inverse': '相反的', 'invested': '投资的', 'investigative': '调查的',
        'invisible': '看不见的', 'involuntary': '非自愿的', 'involved': '涉及的',
        'irrational': '不合理的', 'irregular': '不规则的', 'irrelevant': '无关的',
        'irreplaceable': '不可替代的', 'irresponsible': '不负责任的', 'irritating': '令人恼火的',
        'isolated': '孤立的', 'itching': '渴望的', 'joint': '联合的',
        'judging': '判断的', 'junior': '初级的', 'just': '公正的',
        'keen': '热心的', 'key': '关键的', 'kid': ('kid', '孩子'),
        'kind': '善良的', 'kindly': '和蔼的', 'knowledgeable': '知识渊博的',
        'lacking': '缺乏的', 'lame': '跛脚的', 'lame': '聋哑的',
        'large': '大的', 'largely': '主要地', 'late': '晚的',
        'lateral': '侧面的', 'latest': '最新的', 'latter': '后者的',
        'laudatory': '赞扬的', 'lazy': '懒惰的', 'leading': '领导的',
        'leafy': '多叶的', 'learning': '学习的', 'least': '最小的',
        'leather': '皮革的', 'left': '左边的', 'left-wing': '左翼的',
        'legal': '合法的', 'legendary': '传奇的', 'legible': '清晰的',
        'legitimate': '合法的', 'leisure': '闲暇的', 'lengthy': '冗长的',
        'lesser': '较小的', 'level': '水平的', 'liable': '有责任的',
        'liberal': '自由的', 'licensed': '获许可的', 'lifelong': '终身的',
        'limited': '有限的', 'linear': '线性的', 'liquid': '液体的',
        'listening': '听的', 'literary': '文学的', 'literate': '识字的',
        'lively': '活泼的', 'living': '活着的', 'local': '当地的',
        'locally': '局部地', 'located': '位于的', 'logical': '逻辑的',
        'lonely': '孤独的', 'long': '长的', 'longing': '渴望的',
        'loose': '松的', 'losing': '失败的', 'lost': '丢失的',
        'lovable': '可爱的', 'love': 'love', 'lovely': '可爱的',
        'low': '低的', 'low-income': '低收入', 'loyal': '忠诚的',
        'lucid': '清晰的', 'luck': '运气', 'lucky': '幸运的',
        'ludicrous': '荒谬的', 'luggage': '行李', 'lumber': '木材',
        'lunar': '月球的', 'lunch': '午餐', 'lying': '躺卧的',
        'lyric': '抒情的', 'machinery': '机械的', 'made': '制造的',
        'magic': ('magic', '魔术'), 'magical': '魔术的', 'magnetic': '磁性的',
        'magnificent': '壮丽的', 'main': '主要的', 'mainstream': '主流的',
        'maintainable': '可维持的', 'major': '主要的', 'majority': '大多数的',
        'make': '制造', 'man': ('man', '男人'), 'manageable': '易管理的',
        'managerial': '管理的', 'mandatory': '强制的', 'manly': '男子气概的',
        'manual': '手工的', 'manufacturing': '制造业的', 'many': '许多的',
        'marginal': '边缘的', 'marked': '显著的', 'market': '市场的',
        'married': '已婚的', 'martial': '军事的', 'marvelous': '非凡的',
        'mass': '大规模的', 'massive': '大规模的', 'master': '主人的',
        'matched': '相配的', 'material': '物质的', 'mathematical': '数学的',
        'mature': '成熟的', 'maximum': '最大的', 'mean': '卑鄙的',
        'meaningful': '有意义的', 'meaningless': '无意义的', 'medial': '中间的',
        'median': '中值的', 'medical': '医学的', 'medieval': '中世纪的',
        'meditative': '沉思的', 'medium': '中等的', 'meeting': '会议的',
        'memorable': '值得纪念的', 'memorial': '纪念的', 'mental': '精神的',
        'mentioned': '提到的', 'mentor': '导师', 'merchant': '商人的',
        'mercy': '仁慈', 'mere': '仅仅的', 'merely': '仅仅',
        'merit': '优点', 'merry': '快乐的', 'messy': '混乱的',
        'metallic': '金属的', 'metaphorical': '隐喻的', 'methodical': '有条理的',
        'middle': '中间的', 'midnight': '午夜的', 'mighty': '强大的',
        'mild': '温和的', 'military': '军事的', 'miniature': '微型的',
        'minimal': '最小的', 'minimum': '最小的', 'mining': '采矿的',
        'minister': '部长的', 'minor': '较小的', 'minus': '负的',
        'miraculous': '奇迹般的', 'miserable': '悲惨的', 'misleading': '误导的',
        'miss': '未击中', 'missing': '缺失的', 'missionary': '传教士的',
        'mistaken': '错误的', 'misunderstanding': '误解的', 'mobile': '移动的',
        'mock': '模拟的', 'model': '模型的', 'moderate': '中等的',
        'modern': '现代的', 'modest': '谦虚的', 'modified': '修改的',
        'moist': '潮湿的', 'molecular': '分子的', 'momentary': '瞬间的',
        'monetary': '货币的', 'monopolistic': '垄断的', 'monster': '怪物的',
        'monthly': '每月的', 'monumental': '纪念碑的', 'moral': '道德的',
        'motivation': '动机的', 'motivated': '有动机的', 'motor': '马达的',
        'mountainous': ('mountainous', '多山的'), 'muddy': '泥泞的',
        'multiple': '多重的', 'municipal': '市政的', 'murderous': '谋杀的',
        'muscular': '肌肉的', 'musical': '音乐的', 'mutable': '可变的',
        'mutual': '相互的', 'mysterious': '神秘的', 'mythical': '神话的',
        'naked': '赤裸的', 'namely': '即', 'narrative': '叙事的',
        'narrow': '狭窄的', 'nasty': '下流的', 'nation': '国家的',
        'national': '国家的', 'native': '当地的', 'natural': '自然的',
        'naturally': '自然地', 'naval': '海军的', 'navigable': '可通航的',
        'near': '近的', 'nearby': '附近的', 'nearly': '几乎',
        'neat': '整洁的', 'necessary': '必要的', 'neck': ('neck', '脖子'),
        'need': '需要', 'needle': ('needle', '针'), 'negative': '消极的',
        'negotiable': '可协商的', 'neighbor': ('neighbor', '邻居'), 'neighboring': '邻近的',
        'neither': '两者都不', 'nephew': ('nephew', '侄子'), 'nervous': '紧张的',
        'nested': '嵌套的', 'net': '净的', 'network': '网络的',
        'neutral': '中立的', 'new': '新的', 'news': '新闻的',
        'nice': '美好的', 'night': '夜晚的', 'nine': '九',
        'nineteen': '十九', 'noble': '高尚的', 'nobody': '没有人',
        'nod': ('nod', '点头'), 'noise': '噪音', 'noisy': '嘈杂的',
        'nominal': '名义上的', 'nominate': '提名', 'none': '没有人',
        'nonetheless': '尽管如此', 'noon': ('noon', '中午'), 'norm': '标准的',
        'normal': '正常的', 'normally': '通常', 'north': '北方的',
        'northern': '北方的', 'nose': ('nose', '鼻子'), 'notable': '著名的',
        'note': '记录的', 'noted': '闻名的', 'noticeable': '显而易见的',
        'notorious': '臭名昭著的', 'novel': '新颖的', 'now': '现在的',
        'nowhere': '无处', 'nuclear': '核能的', 'numb': '麻木的',
        'numerous': '众多的', 'nurse': ('nurse', '护士'), 'nursing': '护理的',
        'nut': ('nut', '坚果'), 'object': '客观的', 'objective': '客观的',
        'obligatory': '义务的', 'obliged': '被迫的', 'obscene': '猥亵的',
        'obscure': '模糊的', 'observable': '可观察的', 'observant': '善于观察的',
        'obsolete': '过时的', 'obstinate': '固执的', 'obstructive': '阻碍的',
        'obvious': '明显的', 'occupied': '已占领的', 'occurring': '发生的',
        'odd': '奇怪的', 'odds': 'odd', 'odor': '气味',
        'off': '离开的', 'offensive': '攻击性的', 'offer': '提供的',
        'office': '办公室的', 'official': '官方的', 'offline': '离线的',
        'often': '经常', 'ointment': ('ointment', '药膏'), 'okay': '好的',
        'old': '老的', 'old-fashioned': '老式的', 'olive': ('olive', '橄榄'),
        'Olympic': '奥林匹克', 'omitted': '省略的', 'one': '一个',
        'onion': ('onion', '洋葱'), 'only': '唯一的', 'onset': '开始',
        'open': '开放的', 'opening': '开放的', 'openly': '公开地',
        'operational': '操作的', 'operative': '操作的', 'opinion': '意见的',
        'opponent': '对手的', 'opportunity': '机会的', 'opposite': '相反的',
        'opposition': '反对的', 'optical': '光学的', 'optimal': '最佳的',
        'optimistic': '乐观的', 'optional': '可选择的', 'orange': ('orange', '橙子'),
        'orbit': '轨道的', 'orchestra': '管弦乐的', 'order': '订购的',
        'ordinary': '普通的', 'organic': '有机的', 'organizational': '组织的',
        'oriented': 'oriented', 'original': '原始的', 'ornamental': '装饰的',
        'orphan': '孤儿的', 'out': '外面的', 'outdoor': '室外的',
        'outer': '外部的', 'outgoing': '外出的', 'outlined': '概述的',
        'outrageous': '残暴的', 'outside': '外面的', 'outstanding': '杰出的',
        'outward': '向外的', 'oval': '椭圆形的', 'oven': ('oven', '烤箱'),
        'over': '结束的', 'overall': '全面的', 'overhead': '头上的',
        'overlapping': '重叠的', 'overlooked': '被忽视的', 'overnight': '一夜的',
        'overseas': '海外的', 'overt': '公开的', 'overwhelmed': '被压倒的',
        'overwhelming': '压倒性的', 'overwork': '过度工作的', 'own': '自己的',
        'owner': '所有人的', 'ownership': '所有权', 'oxygen': '氧气的',
    }
    return adj_mapping.get(word.lower(), '某种')

def main():
    # Load the vocabulary
    with open('/Users/mac/openclaw-projects/wordgame/WordGame/Resources/Vocabularies/high_school_3500.json', 'r', encoding='utf-8') as f:
        data = json.load(f)

    words = data['words']
    updated_count = 0
    template_count = 0

    for word_entry in words:
        # Skip if already has a sentence
        if word_entry.get('sentence'):
            continue

        word = word_entry.get('word', '')
        meaning = word_entry.get('meaning', '')

        # Generate sentence
        sentence, translation = get_sentence(word, meaning)
        word_entry['sentence'] = sentence
        word_entry['sentenceTranslation'] = translation
        updated_count += 1
        if word.lower() in SENTENCE_TEMPLATES:
            template_count += 1

    print(f'Updated {updated_count} words with example sentences.')
    print(f'Used template matches: {template_count}')

    # Save the updated vocabulary
    output_path = '/Users/mac/openclaw-projects/wordgame/WordGame/Resources/Vocabularies/high_school_3500.json'
    with open(output_path, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    print(f'Saved to {output_path}')

if __name__ == '__main__':
    main()
